2024-12-30 13:00:02,261 - DEBUG - This is a debug message.
2024-12-30 13:00:02,261 - INFO - This is an info message.
2024-12-30 13:00:02,261 - ERROR - This is an error message.
2024-12-30 13:00:02,261 - DEBUG - Using proactor: IocpProactor
2024-12-30 13:00:02,265 - INFO - Server is running on 127.0.0.1:12345
2024-12-30 13:03:42,238 - DEBUG - This is a debug message.
2024-12-30 13:03:42,239 - INFO - This is an info message.
2024-12-30 13:03:42,239 - ERROR - This is an error message.
2024-12-30 13:03:42,239 - DEBUG - Using proactor: IocpProactor
2024-12-30 13:03:42,241 - INFO - Server is running on 127.0.0.1:12345
2024-12-30 13:03:45,533 - INFO - New connection from ('127.0.0.1', 56310)
2024-12-30 13:03:45,565 - INFO - [INFO] Shared key established with ('127.0.0.1', 56310): 02000000000000000000000000000000
2024-12-30 13:03:48,464 - INFO - Processing command: & C:/msys64/ucrt64/bin/python3.11.exe "c:/Users/enosh/Desktop/Coursework 25'/Network Systems Development/Client-Server network/Client.py"
2024-12-30 13:03:48,464 - ERROR - [ERROR RESPONSE] Unknown device '&'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2024-12-30 13:03:48,464 - INFO - Validation error: ruJ23mHGUj3fiNuAcf0U/2zYEuotJoeLjb0BwAssGnlqJmH4L2vOp3OpgjrNjLB881GCA7SHyHZrgkSoO6xpwaHN6w3/eBXzCkDJ8loaIiUqOagIY3nF/ZqEEo7S8WGAwHeNJU15FVbuONrUGmY3G2gmcfWdcK45IOejty0QCOI=
2024-12-30 13:03:53,969 - INFO - Processing command: & C:/msys64/ucrt64/bin/python3.11.exe "c:/Users/enosh/Desktop/Coursework 25'/Network Systems Development/Client-Server network/Client.py"
2024-12-30 13:03:53,969 - ERROR - [ERROR RESPONSE] Unknown device '&'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2024-12-30 13:03:53,970 - INFO - Validation error: 6NfLq+JOLArWTZClccMRfkmxXoJvJO+yuYqJ3ONT1p5R9KkJ2RKwIzZO6waVa+1r45CTP5s6gU6+eynxIEo6TowCY49dmIcF6Z4lL8EG2sjIs59eGOUEJWPQD026VeCbm8tOD6jW75m05Zkbj1QHo4DuBLc+ke1QGNYa9mAUQk8=
2024-12-30 13:03:57,795 - INFO - Processing command: & C:/msys64/ucrt64/bin/python3.11.exe "c:/Users/enosh/Desktop/Coursework 25'/Network Systems Development/Client-Server network/Client.py"
2024-12-30 13:03:57,795 - ERROR - [ERROR RESPONSE] Unknown device '&'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2024-12-30 13:03:57,795 - INFO - Validation error: KeaZhLpwUS/Uk8nQhqD0b3QtxtKdOzr/ek3TFH/jYGQiaAISwBikbOWgTKplic5n+qDLI/NYEDIz55jljqlEGe6yi+cdyjqX8YbodZ5jIRTGqUgqDKm9SOAXijB8Y6aYjBab7p2tFf9u7HaFG59M50roLx0yUn6WKufWcJXZgoM=
2024-12-30 13:04:48,283 - DEBUG - This is a debug message.
2024-12-30 13:04:48,283 - INFO - This is an info message.
2024-12-30 13:04:48,284 - ERROR - This is an error message.
2024-12-30 13:04:48,284 - DEBUG - Using proactor: IocpProactor
2024-12-30 13:04:48,287 - INFO - Server is running on 127.0.0.1:12345
2024-12-30 13:05:00,572 - INFO - New connection from ('127.0.0.1', 56347)
2024-12-30 13:05:00,605 - INFO - [INFO] Shared key established with ('127.0.0.1', 56347): 02000000000000000000000000000000
2024-12-30 13:05:04,997 - INFO - New connection from ('127.0.0.1', 56350)
2024-12-30 13:05:05,025 - INFO - [INFO] Shared key established with ('127.0.0.1', 56350): 08000000000000000000000000000000
2024-12-30 13:05:08,495 - INFO - New connection from ('127.0.0.1', 56353)
2024-12-30 13:05:08,523 - INFO - [INFO] Shared key established with ('127.0.0.1', 56353): 10000000000000000000000000000000
2024-12-30 13:05:18,968 - INFO - Processing command: light on
2024-12-30 13:05:27,023 - INFO - Processing command: light off
2024-12-30 13:05:35,967 - INFO - Processing command: thermostat get
2024-12-30 13:05:53,329 - WARNING - [SERVER] Client ('127.0.0.1', 56350) disconnected abruptly.
2024-12-30 13:05:53,856 - WARNING - [SERVER] Client ('127.0.0.1', 56353) disconnected abruptly.
2024-12-30 13:05:57,265 - INFO - Processing command: light on
2024-12-30 13:07:01,204 - INFO - Processing command: light on
2024-12-30 13:11:24,253 - DEBUG - This is a debug message.
2024-12-30 13:11:24,254 - INFO - This is an info message.
2024-12-30 13:11:24,254 - ERROR - This is an error message.
2024-12-30 13:11:24,254 - DEBUG - Using proactor: IocpProactor
2024-12-30 13:11:24,257 - INFO - Server is running on 127.0.0.1:12345
2024-12-30 13:11:30,733 - INFO - New connection from ('127.0.0.1', 56429)
2024-12-30 13:11:30,761 - INFO - [INFO] Shared key established with ('127.0.0.1', 56429): 10000000000000000000000000000000
2024-12-30 13:11:34,390 - INFO - Processing command: light on
2024-12-30 13:11:37,277 - INFO - Processing command: light off
2024-12-30 13:11:40,935 - INFO - Processing command: thermostat get
2024-12-30 13:11:45,573 - INFO - Processing command: dhhdijd
2024-12-30 13:11:45,573 - ERROR - [ERROR RESPONSE] Invalid command format. Must include a device and action (e.g., 'light on').
2024-12-30 13:11:45,573 - INFO - Validation error: UQxdyNtvXv8dP54F7sNbJck8dVcfgJ3lpU361gRtdrsDGXacNacqQQLy/JxDyMC4kC53YdMiRhwNDsqJleOKDgy/pthV28BmRQ+AgzudyiwdmfOZ1KeVEHDynvaEqAFmDnwezWvtWsmN8j5ufhVaDQ==
2024-12-30 13:13:31,823 - DEBUG - This is a debug message.
2024-12-30 13:13:31,824 - INFO - This is an info message.
2024-12-30 13:13:31,824 - ERROR - This is an error message.
2024-12-30 13:13:31,825 - DEBUG - Using proactor: IocpProactor
2024-12-30 13:13:31,829 - INFO - Server is running on 127.0.0.1:12345
2024-12-30 13:13:42,611 - INFO - New connection from ('127.0.0.1', 56472)
2024-12-30 13:13:42,660 - INFO - [INFO] Shared key established with ('127.0.0.1', 56472): 10000000000000000000000000000000
2024-12-30 13:13:46,817 - INFO - New connection from ('127.0.0.1', 56477)
2024-12-30 13:13:46,839 - INFO - [INFO] Shared key established with ('127.0.0.1', 56477): 01000000000000000000000000000000
2024-12-30 13:13:50,026 - INFO - New connection from ('127.0.0.1', 56480)
2024-12-30 13:13:50,058 - INFO - [INFO] Shared key established with ('127.0.0.1', 56480): 40000000000000000000000000000000
2024-12-30 13:13:58,456 - INFO - Processing command: light on
2024-12-30 13:14:04,267 - INFO - Processing command: light off
2024-12-30 13:22:07,734 - DEBUG - This is a debug message.
2024-12-30 13:22:07,734 - INFO - This is an info message.
2024-12-30 13:22:07,734 - ERROR - This is an error message.
2024-12-30 13:22:07,734 - DEBUG - Using proactor: IocpProactor
2024-12-30 13:22:07,736 - INFO - Server is running on 127.0.0.1:12345
2024-12-30 13:22:18,146 - INFO - New connection from ('127.0.0.1', 56886)
2024-12-30 13:22:18,163 - INFO - [INFO] Shared key established with ('127.0.0.1', 56886): 40000000000000000000000000000000
2024-12-30 13:22:22,410 - INFO - New connection from ('127.0.0.1', 56889)
2024-12-30 13:22:22,428 - INFO - [INFO] Shared key established with ('127.0.0.1', 56889): 10000000000000000000000000000000
2024-12-30 13:22:25,414 - INFO - New connection from ('127.0.0.1', 56892)
2024-12-30 13:22:25,429 - INFO - [INFO] Shared key established with ('127.0.0.1', 56892): 04000000000000000000000000000000
2024-12-30 13:22:28,707 - INFO - Processing command: light on
2024-12-30 13:22:34,598 - INFO - Processing command: light off
2024-12-30 13:22:41,047 - INFO - Processing command: thermostat get
2024-12-30 13:23:02,367 - INFO - Processing command: thermostat set 56
2024-12-30 13:23:02,376 - ERROR - [ERROR RESPONSE] Thermostat set to 56�C
2024-12-30 13:23:17,889 - INFO - Processing command: thermostat set 56
2024-12-30 13:23:17,889 - ERROR - [ERROR RESPONSE] Thermostat set to 56�C
2024-12-30 13:23:20,930 - INFO - Processing command: light on
2024-12-30 13:23:40,051 - INFO - Processing command: fan off
2024-12-30 13:23:55,754 - INFO - Processing command: fan high
2024-12-30 13:24:07,238 - INFO - [SERVER] Client ('127.0.0.1', 56892) disconnected.
2024-12-30 14:56:19,488 - DEBUG - Using proactor: IocpProactor
2024-12-30 14:56:19,491 - INFO - Server is running on 127.0.0.1:12345
2024-12-30 14:56:38,302 - INFO - New connection from ('127.0.0.1', 60313)
2024-12-30 14:56:38,321 - INFO - [INFO] Shared key established with ('127.0.0.1', 60313): 10000000000000000000000000000000
2024-12-30 14:56:42,647 - INFO - New connection from ('127.0.0.1', 60322)
2024-12-30 14:56:42,663 - INFO - [INFO] Shared key established with ('127.0.0.1', 60322): 01000000000000000000
2024-12-30 14:56:42,663 - ERROR - [DECRYPTION ERROR] Message too short for valid IV.
2024-12-30 14:56:42,663 - ERROR - [ENCRYPTION ERROR] Incorrect AES key length (10 bytes)
2024-12-30 14:56:42,663 - ERROR - [SERVER ERROR] Unexpected error: 'NoneType' object has no attribute 'encode'
2024-12-30 14:56:52,268 - INFO - New connection from ('127.0.0.1', 60327)
2024-12-30 14:56:52,286 - INFO - [INFO] Shared key established with ('127.0.0.1', 60327): 20000000000000000000000000000000
2024-12-30 14:56:58,793 - INFO - New connection from ('127.0.0.1', 60330)
2024-12-30 14:56:58,811 - INFO - [INFO] Shared key established with ('127.0.0.1', 60330): 04000000000000000000000000000000
2024-12-30 14:57:02,743 - INFO - Processing command: python client.py
2024-12-30 14:57:02,743 - ERROR - [ERROR RESPONSE] Unknown device 'python'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2024-12-30 14:57:02,743 - INFO - Validation error: ApBJ3nSV/3Gk6jAf3PCy84XszzAmi2KeIJxgYwaRMoo8Fo9oRSZf303TC/PL1uEYZ4mfSdT1HMdTN13ANZLRJxoSXnD66V8B9Xf9Pk0NoNh2vwaVBE7wRFT+sIdOV0ULj5g4S4OOSv+WE0rXVeqJtqF9CrcwsoEXx94y6EcwjSM=
2024-12-30 14:57:05,992 - INFO - Processing command: 
2024-12-30 14:57:05,992 - ERROR - [ERROR RESPONSE] Invalid command format. Must include a device and action (e.g., 'light on').
2024-12-30 14:57:05,992 - INFO - Validation error: 8XsBJTlOurOT9p6HlKwLIn+C/wElX8QfdaG/ih+53W5hYHsXGMv/GOIRrLKPZUPfpzvgZsiedfbLH55wQrjmtlzRT38stxUaML7+yUVibWcW2wzmn+rtgemHYYPRXHAObBw2AjZt/CW0ZvpmWef19w==
2024-12-30 14:57:13,692 - INFO - Processing command: python client.py
2024-12-30 14:57:13,692 - ERROR - [ERROR RESPONSE] Unknown device 'python'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2024-12-30 14:57:13,692 - INFO - Validation error: JSHibVYlT/Ob50ATdsbW1ploKAwEmuDvCr9uOrSOZrqSmUmaerywkk4YutmbnM1sgNIulUGewOYi/835v6ztkPaqRuYy2/IUV7CyDHlSGHeqEhvO2W3ezi9vOHD77ud0lFeKWSOaCiysd6jzSI8m2x3JX9qgCRACKeq2g/q74xU=
2024-12-30 14:57:15,856 - INFO - Processing command: python client.py
2024-12-30 14:57:15,856 - ERROR - [ERROR RESPONSE] Unknown device 'python'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2024-12-30 14:57:15,856 - INFO - Validation error: oF3PvWShX8iIlTWLepmg5jVN9aKy0tP924YPuW/e+itgtU3TnGouUgqWF7D2/stG0YlKS5xVtE0WK11Maj2aAk+Fi840ATQTKwElliXFoKtiLSlwnhC+l4kdfwBSMWakJpuBPYyIS0B34YhHklVnr7vO8yQhXI/wxoZw1nJqReY=
2024-12-30 14:57:19,421 - INFO - Processing command: light on
2024-12-30 14:57:22,450 - INFO - Processing command: light off
2024-12-30 14:57:50,753 - INFO - Processing command: light on
2024-12-30 14:58:06,850 - INFO - Processing command: light off
2024-12-30 14:58:17,289 - DEBUG - Using proactor: IocpProactor
2024-12-30 14:58:17,291 - INFO - Server is running on 127.0.0.1:12345
2024-12-30 14:58:27,054 - INFO - New connection from ('127.0.0.1', 60363)
2024-12-30 14:58:27,073 - INFO - [INFO] Shared key established with ('127.0.0.1', 60363): 04000000000000000000000000000000
2024-12-30 14:58:44,381 - INFO - New connection from ('127.0.0.1', 60366)
2024-12-30 14:58:44,397 - INFO - [INFO] Shared key established with ('127.0.0.1', 60366): 02000000000000000000000000000000
2024-12-30 14:58:48,236 - INFO - Processing command: light on
2024-12-30 14:59:01,877 - INFO - Processing command: light off
2024-12-30 14:59:04,728 - INFO - [SERVER] Client ('127.0.0.1', 60363) disconnected.
2024-12-30 14:59:09,843 - INFO - [SERVER] Client ('127.0.0.1', 60366) disconnected.
2024-12-30 14:59:38,532 - DEBUG - Using proactor: IocpProactor
2024-12-30 14:59:38,534 - INFO - Server is running on 127.0.0.1:12345
2024-12-30 14:59:50,616 - INFO - New connection from ('127.0.0.1', 60386)
2024-12-30 14:59:50,632 - INFO - [INFO] Shared key established with ('127.0.0.1', 60386): 02000000000000000000000000000000
2024-12-30 14:59:57,223 - INFO - New connection from ('127.0.0.1', 60389)
2024-12-30 14:59:57,239 - INFO - [INFO] Shared key established with ('127.0.0.1', 60389): 20000000000000000000000000000000
2024-12-30 15:00:09,486 - INFO - Processing command: light on
2024-12-30 15:06:26,968 - DEBUG - Using proactor: IocpProactor
2024-12-30 15:06:26,970 - INFO - Server is running on 127.0.0.1:12345
2024-12-30 15:06:43,614 - INFO - New connection from ('127.0.0.1', 60510)
2024-12-30 15:06:43,631 - INFO - [INFO] Shared key established with ('127.0.0.1', 60510): 01000000000000000000000000000000
2024-12-30 15:06:47,970 - INFO - Processing command: light on
2024-12-30 15:06:47,971 - INFO - [SERVER] Client ('127.0.0.1', 60510) disconnected.
2024-12-30 15:07:07,955 - INFO - New connection from ('127.0.0.1', 60519)
2024-12-30 15:07:07,971 - INFO - [INFO] Shared key established with ('127.0.0.1', 60519): 02000000000000000000000000000000
2024-12-30 15:07:23,106 - INFO - New connection from ('127.0.0.1', 60533)
2024-12-30 15:07:23,122 - INFO - [INFO] Shared key established with ('127.0.0.1', 60533): 02000000000000000000000000000000
2024-12-30 15:07:25,766 - INFO - Processing command: light on
2024-12-30 15:07:25,767 - INFO - [SERVER] Client ('127.0.0.1', 60533) disconnected.
2024-12-30 15:07:34,677 - INFO - Processing command: light off
2024-12-30 15:07:34,683 - INFO - [SERVER] Client ('127.0.0.1', 60519) disconnected.
2024-12-30 15:22:46,998 - DEBUG - Using proactor: IocpProactor
2024-12-30 15:22:47,003 - INFO - Server is running on 127.0.0.1:12345
2024-12-30 15:22:54,928 - INFO - New connection from ('127.0.0.1', 61011)
2024-12-30 15:22:54,942 - INFO - [INFO] Shared key established with ('127.0.0.1', 61011): 02000000000000000000000000000000
2024-12-30 15:23:03,335 - INFO - New connection from ('127.0.0.1', 61019)
2024-12-30 15:23:03,354 - INFO - [INFO] Shared key established with ('127.0.0.1', 61019): 04000000000000000000000000000000
2024-12-30 15:23:06,953 - INFO - Processing command: light on
2024-12-30 15:23:06,962 - INFO - [SERVER] Client ('127.0.0.1', 61019) disconnected.
2024-12-30 15:27:40,298 - DEBUG - Using proactor: IocpProactor
2024-12-30 15:27:40,300 - INFO - Server is running on 127.0.0.1:12345
2024-12-30 15:27:48,916 - INFO - New connection from ('127.0.0.1', 61136)
2024-12-30 15:27:48,932 - INFO - [INFO] Shared key established with ('127.0.0.1', 61136): 20000000000000000000000000000000
2024-12-30 15:27:56,221 - INFO - New connection from ('127.0.0.1', 61139)
2024-12-30 15:27:56,238 - INFO - [INFO] Shared key established with ('127.0.0.1', 61139): 04000000000000000000000000000000
2024-12-30 15:27:58,695 - INFO - Processing command: light on
2024-12-30 15:27:58,697 - INFO - [SERVER] Client ('127.0.0.1', 61139) disconnected.
2024-12-30 15:28:14,871 - INFO - Processing command: light on
2024-12-30 15:28:14,873 - INFO - [SERVER] Client ('127.0.0.1', 61136) disconnected.
2024-12-30 15:52:01,284 - DEBUG - Using proactor: IocpProactor
2024-12-30 15:52:01,286 - INFO - Server is running on 127.0.0.1:12345
2024-12-30 15:53:21,103 - INFO - New connection from ('127.0.0.1', 62242)
2024-12-30 15:53:21,119 - INFO - [INFO] Shared key established with ('127.0.0.1', 62242): 08000000000000000000000000000000
2024-12-30 15:53:30,830 - INFO - New connection from ('127.0.0.1', 62248)
2024-12-30 15:53:30,845 - INFO - [INFO] Shared key established with ('127.0.0.1', 62248): 04000000000000000000000000000000
2024-12-30 15:53:35,157 - INFO - Processing command: light on
2024-12-30 15:53:35,160 - INFO - [SERVER] Client ('127.0.0.1', 62248) disconnected.
2024-12-31 12:17:13,049 - DEBUG - Using proactor: IocpProactor
2024-12-31 12:17:13,052 - INFO - Server is running on 127.0.0.1:12345
2024-12-31 12:17:13,434 - INFO - New connection from ('127.0.0.1', 61209)
2024-12-31 12:17:13,454 - INFO - [INFO] Shared key established with ('127.0.0.1', 61209): 04000000000000000000000000000000
2024-12-31 12:17:29,356 - INFO - Processing command: light on
2024-12-31 12:17:29,361 - INFO - [SERVER] Client ('127.0.0.1', 61209) disconnected.
2024-12-31 12:24:24,069 - DEBUG - Using proactor: IocpProactor
2024-12-31 12:24:24,071 - INFO - Server is running on 127.0.0.1:12345
2024-12-31 12:24:27,301 - INFO - New connection from ('127.0.0.1', 62734)
2024-12-31 12:24:27,317 - INFO - [INFO] Shared key established with ('127.0.0.1', 62734): 01000000000000000000000000000000
2024-12-31 12:24:30,688 - INFO - Processing command: light on
2024-12-31 12:24:30,690 - INFO - [SERVER] Client ('127.0.0.1', 62734) disconnected.
2024-12-31 12:31:48,126 - DEBUG - Using proactor: IocpProactor
2024-12-31 12:31:48,128 - INFO - Server is running on 127.0.0.1:12345
2024-12-31 12:31:50,380 - INFO - New connection from ('127.0.0.1', 62958)
2024-12-31 12:31:50,398 - INFO - [INFO] Shared key established with ('127.0.0.1', 62958): 80000000000000000000000000000000
2024-12-31 12:31:53,736 - INFO - Processing command: light on
2024-12-31 12:32:06,970 - WARNING - [SERVER] Client ('127.0.0.1', 62958) disconnected abruptly.
2024-12-31 12:32:15,147 - INFO - New connection from ('127.0.0.1', 62966)
2024-12-31 12:32:15,164 - INFO - [INFO] Shared key established with ('127.0.0.1', 62966): 80000000000000000000000000000000
2024-12-31 12:32:18,054 - INFO - Processing command: light on
2024-12-31 12:34:20,618 - WARNING - [SERVER] Client ('127.0.0.1', 62966) disconnected abruptly.
2024-12-31 12:34:22,483 - INFO - New connection from ('127.0.0.1', 63010)
2024-12-31 12:34:22,500 - INFO - [INFO] Shared key established with ('127.0.0.1', 63010): 01000000000000000000000000000000
2024-12-31 12:34:26,806 - INFO - Processing command: light on
2024-12-31 12:34:26,807 - INFO - [SERVER] Client ('127.0.0.1', 63010) disconnected.
2024-12-31 12:38:53,430 - DEBUG - Using proactor: IocpProactor
2024-12-31 12:38:53,432 - INFO - Server is running on 127.0.0.1:12345
2024-12-31 12:38:57,243 - INFO - New connection from ('127.0.0.1', 63240)
2024-12-31 12:38:57,260 - INFO - [INFO] Shared key established with ('127.0.0.1', 63240): 01000000000000000000000000000000
2024-12-31 12:39:00,571 - INFO - Processing command: light on
2024-12-31 12:39:00,573 - INFO - [SERVER] Client ('127.0.0.1', 63240) disconnected.
2024-12-31 12:39:11,964 - INFO - New connection from ('127.0.0.1', 63244)
2024-12-31 12:39:11,981 - INFO - [INFO] Shared key established with ('127.0.0.1', 63244): 01000000000000000000000000000000
2024-12-31 12:39:15,169 - WARNING - [SERVER] Client ('127.0.0.1', 63244) disconnected abruptly.
2024-12-31 12:39:21,760 - DEBUG - Using proactor: IocpProactor
2024-12-31 12:39:21,761 - INFO - Server is running on 127.0.0.1:12345
2024-12-31 12:39:36,282 - INFO - New connection from ('127.0.0.1', 63255)
2024-12-31 12:39:36,298 - INFO - [INFO] Shared key established with ('127.0.0.1', 63255): 80000000000000000000000000000000
2024-12-31 12:39:40,511 - INFO - Processing command: light on
2024-12-31 12:39:40,514 - INFO - [SERVER] Client ('127.0.0.1', 63255) disconnected.
2024-12-31 12:39:51,255 - INFO - New connection from ('127.0.0.1', 63258)
2024-12-31 12:39:51,272 - INFO - [INFO] Shared key established with ('127.0.0.1', 63258): 020000000000000000000000000000
2024-12-31 12:39:51,273 - ERROR - [DECRYPTION ERROR] Message too short for valid IV.
2024-12-31 12:39:51,273 - ERROR - [ENCRYPTION ERROR] Incorrect AES key length (15 bytes)
2024-12-31 12:39:51,273 - ERROR - [SERVER ERROR] Unexpected error: 'NoneType' object has no attribute 'encode'
2024-12-31 13:30:03,874 - DEBUG - Using proactor: IocpProactor
2024-12-31 13:30:03,875 - INFO - Server is running on 127.0.0.1:12345
2024-12-31 13:30:13,150 - INFO - New connection from ('127.0.0.1', 63985)
2024-12-31 13:30:13,168 - INFO - [INFO] Shared key established with ('127.0.0.1', 63985): 80000000000000000000000000000000
2024-12-31 13:30:16,376 - INFO - Processing command: light on
2024-12-31 13:30:16,377 - INFO - [SERVER] Client ('127.0.0.1', 63985) disconnected.
2024-12-31 13:30:31,392 - INFO - New connection from ('127.0.0.1', 63989)
2024-12-31 13:30:31,408 - INFO - [INFO] Shared key established with ('127.0.0.1', 63989): 04000000000000000000000000000000
2024-12-31 13:30:34,275 - INFO - Processing command: light on
2024-12-31 13:30:34,276 - INFO - [SERVER] Client ('127.0.0.1', 63989) disconnected.
2024-12-31 13:31:02,226 - DEBUG - This is a debug message.
2024-12-31 13:31:02,227 - INFO - This is an info message.
2024-12-31 13:31:02,227 - ERROR - This is an error message.
2024-12-31 13:31:02,227 - DEBUG - Using proactor: IocpProactor
2024-12-31 13:31:02,229 - INFO - Server is running on 127.0.0.1:12345
2024-12-31 13:31:12,434 - INFO - New connection from ('127.0.0.1', 63998)
2024-12-31 13:31:12,450 - INFO - [INFO] Shared key established with ('127.0.0.1', 63998): 04000000000000000000000000000000
2024-12-31 13:31:14,869 - INFO - Processing command: light on
2024-12-31 13:31:14,870 - INFO - [SERVER] Client ('127.0.0.1', 63998) disconnected.
2024-12-31 13:31:55,131 - DEBUG - This is a debug message.
2024-12-31 13:31:55,131 - INFO - This is an info message.
2024-12-31 13:31:55,131 - ERROR - This is an error message.
2024-12-31 13:31:55,131 - DEBUG - Using proactor: IocpProactor
2024-12-31 13:31:55,133 - INFO - Server is running on 127.0.0.1:12345
2024-12-31 13:32:04,391 - INFO - New connection from ('127.0.0.1', 64021)
2024-12-31 13:32:04,408 - INFO - [INFO] Shared key established with ('127.0.0.1', 64021): 10000000000000000000000000000000
2024-12-31 13:32:07,128 - INFO - Processing command: light on
2024-12-31 13:32:10,019 - INFO - Processing command: light off
2024-12-31 13:32:19,134 - INFO - New connection from ('127.0.0.1', 64027)
2024-12-31 13:32:19,150 - INFO - [INFO] Shared key established with ('127.0.0.1', 64027): 040000
2024-12-31 13:32:19,151 - ERROR - [DECRYPTION ERROR] Message too short for valid IV.
2024-12-31 13:32:19,152 - ERROR - [ENCRYPTION ERROR] Incorrect AES key length (3 bytes)
2024-12-31 13:32:19,152 - ERROR - [SERVER ERROR] Unexpected error: 'NoneType' object has no attribute 'encode'
2024-12-31 13:32:19,152 - ERROR - [ERROR RESPONSE] An unexpected server error occurred.
2024-12-31 13:32:39,327 - INFO - New connection from ('127.0.0.1', 64035)
2024-12-31 13:32:39,343 - INFO - [INFO] Shared key established with ('127.0.0.1', 64035): 10000000
2024-12-31 13:32:39,344 - ERROR - [DECRYPTION ERROR] Message too short for valid IV.
2024-12-31 13:32:39,344 - ERROR - [ENCRYPTION ERROR] Incorrect AES key length (4 bytes)
2024-12-31 13:32:39,345 - ERROR - [SERVER ERROR] Unexpected error: 'NoneType' object has no attribute 'encode'
2024-12-31 13:32:39,345 - ERROR - [ERROR RESPONSE] An unexpected server error occurred.
2024-12-31 13:41:59,910 - DEBUG - Using proactor: IocpProactor
2024-12-31 13:41:59,912 - INFO - Server is running on 127.0.0.1:12345
2024-12-31 13:42:05,269 - INFO - New connection from ('127.0.0.1', 64379)
2024-12-31 13:42:05,286 - INFO - [INFO] Shared key established with ('127.0.0.1', 64379): 80000000000000000000000000000000
2024-12-31 13:42:08,041 - INFO - Processing command: light on
2024-12-31 13:42:12,319 - INFO - Processing command: light off
2024-12-31 13:42:19,497 - INFO - New connection from ('127.0.0.1', 64386)
2024-12-31 13:42:19,513 - INFO - [INFO] Shared key established with ('127.0.0.1', 64386): 10000000000000000000000000000000
2024-12-31 13:42:22,014 - INFO - Processing command: light on
2024-12-31 13:42:28,181 - INFO - Processing command: light off thermostat get
2024-12-31 13:42:50,547 - INFO - Processing command: light on
2024-12-31 13:43:03,744 - INFO - Processing command: thermostat set67
2024-12-31 13:43:03,744 - ERROR - [ERROR RESPONSE] Invalid action 'set67' for device 'thermostat'. Valid actions are: get, set.
2024-12-31 13:43:03,744 - INFO - Validation error: tJtHavqxURIAORwimdnMx8Q/ub5ZWjZDrPnjsnkooP4+kzBix1cIaBVbdvIRn1fTOcVgu0R9oNzO/prPibDGAkz8hmCBQiOfJlXyFvoK2uqANeQb5pgkjp8j+c54mh0+C1Rqda+maWMGbO+Jc4wLRA==
2024-12-31 13:43:08,006 - INFO - Processing command: thermostat set 56
2024-12-31 13:43:08,006 - ERROR - [ERROR RESPONSE] Thermostat set to 56�C
2024-12-31 13:43:19,880 - INFO - Processing command: fan low
2024-12-31 13:43:29,891 - INFO - Processing command: fan high
2024-12-31 14:03:29,024 - DEBUG - Using proactor: IocpProactor
2024-12-31 14:03:29,027 - INFO - Loaded device states: {'light': {'state': 'on', 'temperature': None, 'speed': None, 'lock_time': None}, 'thermostat': {'state': 'on', 'temperature': 56, 'speed': None, 'lock_time': None}, 'fan': {'state': 'on', 'temperature': None, 'speed': 'high', 'lock_time': None}, 'smart lock': {'state': 'locked', 'temperature': None, 'speed': None, 'lock_time': 'lock 5:45'}, 'camera': {'state': 'on', 'temperature': None, 'speed': None, 'lock_time': None}, 'speaker': {'state': 'off', 'temperature': None, 'speed': None, 'lock_time': None}}
2024-12-31 14:03:29,028 - INFO - Server is running on 127.0.0.1:12345
2024-12-31 14:03:33,306 - INFO - New connection from ('127.0.0.1', 65177)
2024-12-31 14:03:33,323 - INFO - [INFO] Shared key established with ('127.0.0.1', 65177): 04000000000000000000000000000000
2024-12-31 14:03:38,035 - INFO - Processing command: light on
2024-12-31 14:04:03,164 - INFO - Processing command: thermostat get
2024-12-31 14:04:18,245 - INFO - Processing command: thermostat set 45
2024-12-31 14:04:26,208 - INFO - Processing command: thermostat set 56
2024-12-31 14:04:35,417 - INFO - Processing command: thermostat 90
2024-12-31 14:04:35,417 - ERROR - [ERROR RESPONSE] Invalid action '90' for device 'thermostat'. Valid actions are: get, set.
2024-12-31 14:04:35,418 - INFO - Validation error: 1DnLu36CiL7i5iDCbcUPl4KCS61Z+VbEqjrmFhabkhLujQd3u1JHMkwBwJPI8tGcsEVGrQQghJjk6W4UGDtX92TIYQmACF8dROcTANDTPhnYeLpzBXL8i9sZniPtlJpk396noYGYAPiIDAUCe70QXg==
2024-12-31 15:04:48,388 - DEBUG - Using proactor: IocpProactor
2024-12-31 15:04:48,391 - INFO - Loaded device states: {'light': {'state': 'on', 'temperature': None, 'speed': None, 'lock_time': None}, 'thermostat': {'state': 'on', 'temperature': 56, 'speed': None, 'lock_time': None}, 'fan': {'state': 'on', 'temperature': None, 'speed': 'high', 'lock_time': None}, 'smart lock': {'state': 'locked', 'temperature': None, 'speed': None, 'lock_time': 'lock 5:45'}, 'camera': {'state': 'on', 'temperature': None, 'speed': None, 'lock_time': None}, 'speaker': {'state': 'off', 'temperature': None, 'speed': None, 'lock_time': None}}
2024-12-31 15:04:48,392 - INFO - Server is running on 127.0.0.1:12345
2024-12-31 15:04:51,365 - INFO - New connection from ('127.0.0.1', 50657)
2024-12-31 15:04:51,383 - INFO - [INFO] Shared key established with ('127.0.0.1', 50657): 08000000000000000000000000000000
2024-12-31 15:04:56,692 - INFO - Processing command: light on
2024-12-31 15:05:08,759 - INFO - Processing command: light off
2024-12-31 15:05:12,384 - INFO - Processing command: fan on
2024-12-31 15:05:15,689 - INFO - Processing command: fan off
2024-12-31 15:10:13,526 - DEBUG - Using proactor: IocpProactor
2024-12-31 15:10:13,528 - INFO - Loaded device states: {'light': {'state': 'off', 'temperature': None, 'speed': None, 'lock_time': None}, 'thermostat': {'state': 'on', 'temperature': 56, 'speed': None, 'lock_time': None}, 'fan': {'state': 'off', 'temperature': None, 'speed': None, 'lock_time': None}, 'smart lock': {'state': 'locked', 'temperature': None, 'speed': None, 'lock_time': 'lock 5:45'}, 'camera': {'state': 'on', 'temperature': None, 'speed': None, 'lock_time': None}, 'speaker': {'state': 'off', 'temperature': None, 'speed': None, 'lock_time': None}}
2024-12-31 15:10:13,528 - INFO - Server is running on 127.0.0.1:12345
2024-12-31 15:11:56,446 - INFO - New connection from ('127.0.0.1', 51096)
2024-12-31 15:11:56,465 - INFO - [INFO] Shared key established with ('127.0.0.1', 51096): 01000000000000000000000000000000
2024-12-31 15:12:00,042 - INFO - Processing command: light on
2024-12-31 15:12:00,052 - INFO - [SERVER] Client ('127.0.0.1', 51096) disconnected.
2024-12-31 15:18:40,277 - DEBUG - Using proactor: IocpProactor
2024-12-31 15:18:40,279 - INFO - Server is running on 127.0.0.1:12345
2024-12-31 15:18:43,633 - INFO - New connection from ('127.0.0.1', 51517)
2024-12-31 15:18:43,651 - INFO - [INFO] Shared key established with ('127.0.0.1', 51517): 04000000000000000000000000000000
2024-12-31 15:18:57,366 - INFO - Processing command: light on
2024-12-31 15:19:08,044 - INFO - Processing command: light off
2024-12-31 15:19:19,704 - INFO - Processing command: thermostat set 67
2024-12-31 15:19:19,714 - ERROR - [ERROR RESPONSE] Thermostat set to 67�C
2024-12-31 15:19:37,114 - INFO - New connection from ('127.0.0.1', 51630)
2024-12-31 15:19:37,132 - INFO - [INFO] Shared key established with ('127.0.0.1', 51630): 01000000000000000000000000000000
2024-12-31 15:19:44,397 - INFO - Processing command: smart lock lock 6:45
2024-12-31 15:19:44,397 - ERROR - [ERROR RESPONSE] Unknown device 'smart'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2024-12-31 15:19:44,397 - INFO - Validation error: 85p7DTa5wmFcb8gVx+IVsl8bAo7Ek/5mnyLJZTZXGaDaCyyaaEFoschhVRUr63muSjNPCzXv08SCeyBt4kUzMy1I9zR9nqZEVim9magmLXLGbOniSTEI7z8e74n9UHMxXidbLz44Sq4b4bi79yF3aitXEe2h5MzqFN1Dl3Bi/d4=
2024-12-31 15:20:08,594 - INFO - Processing command: smart lock lock 12:45pm
2024-12-31 15:20:08,595 - ERROR - [ERROR RESPONSE] Unknown device 'smart'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2024-12-31 15:20:08,595 - INFO - Validation error: F9V3DfhnalgIHeIZKTlfXYUaGITWgZZ2nCTsoFWDtfO3bdzTaaufuMVJxWpGkkL/jG63LmI4QQDeJrh51qJGmDNqgE6PRtV6Ka9ErOUEVPxU46PAwzYGBPMKrKCOzhok7TSohIwc9AYLK3BoLc0PRy2hBEB1+xOIEfCA1RweLDU=
2024-12-31 15:20:33,655 - INFO - Processing command: smart lock unlocked
2024-12-31 15:20:33,655 - ERROR - [ERROR RESPONSE] Unknown device 'smart'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2024-12-31 15:20:33,655 - INFO - Validation error: VSTrr4lZXGcEP3xAdxz63R5vn7W8Uvj0zxVLDRsNskiCoB3Q94uWarCWMFAph0x8sbnBUdIPufrh3KVNzR5QyG6xUC7MWi+lh/vIpUwYuBbWaT3xyPStyDTE2OnD9jUWGK0yI5mgk0zA8uoTTVVdkmXQRXAFHEqQEyG5xCNis+s=
2024-12-31 15:20:54,230 - INFO - Processing command: smart lock unlocked
2024-12-31 15:20:54,230 - ERROR - [ERROR RESPONSE] Unknown device 'smart'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2024-12-31 15:20:54,230 - INFO - Validation error: d1rWvErPyyM8jRmwkPMclvhER1JSeqi9zPGtR3D5j2L4NyOvxW6LIO4pSca5+LsX9HiOo1Rt0iIBVkJT2RQB2DklK+jKE/jwUPvPtxx0M0aUWb0jqfxLyW+3vQzbb1SfbVH2Fab+4nt+n1VVPUFimTniZwwDSNmTce+rDZcScrc=
2024-12-31 15:21:08,292 - INFO - Processing command: light on
2024-12-31 16:29:49,513 - DEBUG - Using proactor: IocpProactor
2024-12-31 16:29:49,521 - INFO - Server is running on 127.0.0.1:12345
2024-12-31 16:29:52,842 - INFO - New connection from ('127.0.0.1', 55906)
2024-12-31 16:29:52,872 - INFO - [INFO] Shared key established with ('127.0.0.1', 55906): 10000000000000000000000000000000
2024-12-31 16:29:56,061 - INFO - Processing command: light on
2024-12-31 16:29:59,181 - INFO - Processing command: fan on
2024-12-31 16:30:01,628 - INFO - Processing command: fan off
2024-12-31 16:30:05,956 - INFO - Processing command: thermostat get
2024-12-31 16:30:12,204 - INFO - Processing command: thermostat set 56
2024-12-31 16:30:12,217 - ERROR - [ERROR RESPONSE] Thermostat set to 56�C
2024-12-31 16:30:25,089 - INFO - New connection from ('127.0.0.1', 55919)
2024-12-31 16:30:25,119 - INFO - [INFO] Shared key established with ('127.0.0.1', 55919): 10000000000000000000000000000000
2024-12-31 16:30:27,669 - INFO - Processing command: light on
2024-12-31 16:30:30,603 - INFO - Processing command: light off
2024-12-31 16:30:33,770 - INFO - Processing command: thermostat get
2024-12-31 16:30:42,554 - INFO - Processing command: speaker on
2024-12-31 16:30:46,393 - INFO - Processing command: speaker off
2024-12-31 16:30:52,104 - INFO - Processing command: camera on
2024-12-31 16:30:56,979 - INFO - Processing command: camera off
2024-12-31 16:31:00,158 - INFO - Processing command: smart lock lock
2024-12-31 16:31:00,158 - ERROR - [ERROR RESPONSE] Unknown device 'smart'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2024-12-31 16:31:00,158 - INFO - Validation error: C7S8ExsTinYfNCQdsuVwCr6HMfM/qCr2VFlVkAAaTKjzNWmnaDWiIkcgoQBNrNb0tp+275x69SdN5G+H8NX0vSisIdLNicd6lGFUf+MD4h9xlPfa3b44DALratH3eSZl339YswpIau4BdZHLU6I0Ljn9Ttw1pkHzDqpK4zTMI1M=
2024-12-31 16:31:08,431 - INFO - Processing command: smart lock lock 5:56
2024-12-31 16:31:08,431 - ERROR - [ERROR RESPONSE] Unknown device 'smart'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2024-12-31 16:31:08,431 - INFO - Validation error: r+SeP/4Ol7y601R6jm0IAQZXoibMWNUIk97SIznQxaJX/FBlyAQwF8kXDb0dyiPkLnviynE1Pzab2tAUENfWEWi+4PMfd/anYPCFJdtFEfQQtN0B+BxOHd5XEeevRCC6SNE5V4wMK345Oe4OQQ/i78/9awL9JTpKSnfpOEO5MjY=
2025-01-02 12:23:06,089 - DEBUG - Using proactor: IocpProactor
2025-01-02 12:23:06,094 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 12:23:06,287 - INFO - New connection from ('127.0.0.1', 52406)
2025-01-02 12:23:06,315 - INFO - [INFO] Shared key established with ('127.0.0.1', 52406): 80000000000000000000000000000000
2025-01-02 12:23:11,879 - INFO - Processing command: light on
2025-01-02 12:23:14,070 - INFO - Processing command: light off
2025-01-02 12:23:18,792 - INFO - Processing command: thermostat get
2025-01-02 12:23:26,008 - INFO - Processing command: thermostat set 56
2025-01-02 12:23:26,009 - ERROR - [ERROR RESPONSE] Thermostat set to 56�C
2025-01-02 12:31:10,383 - DEBUG - Using proactor: IocpProactor
2025-01-02 12:31:10,386 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 12:31:14,334 - INFO - New connection from ('127.0.0.1', 52489)
2025-01-02 12:31:14,361 - INFO - [INFO] Shared key established with ('127.0.0.1', 52489): 80000000000000000000000000000000
2025-01-02 12:31:14,463 - INFO - [SERVER] Client ('127.0.0.1', 52489) disconnected.
2025-01-02 12:31:56,308 - DEBUG - Using proactor: IocpProactor
2025-01-02 12:31:56,311 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 12:31:59,018 - INFO - New connection from ('127.0.0.1', 52501)
2025-01-02 12:31:59,043 - INFO - [INFO] Shared key established with ('127.0.0.1', 52501): 10000000000000000000000000000000
2025-01-02 12:32:03,613 - INFO - Processing command: light on
2025-01-02 12:32:07,944 - INFO - Processing command: thermostat get
2025-01-02 12:32:07,945 - ERROR - Error processing command: tuple indices must be integers or slices, not str
2025-01-02 12:32:07,945 - ERROR - [ERROR RESPONSE] Error: tuple indices must be integers or slices, not str
2025-01-02 12:32:13,850 - INFO - Processing command: thermostat set 56
2025-01-02 12:32:13,850 - ERROR - Error processing command: tuple indices must be integers or slices, not str
2025-01-02 12:32:13,850 - ERROR - [ERROR RESPONSE] Error: tuple indices must be integers or slices, not str
2025-01-02 12:32:29,937 - WARNING - [SERVER] Client ('127.0.0.1', 52501) disconnected abruptly.
2025-01-02 12:33:19,695 - DEBUG - Using proactor: IocpProactor
2025-01-02 12:33:19,698 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 12:33:22,842 - INFO - New connection from ('127.0.0.1', 52522)
2025-01-02 12:33:22,868 - INFO - [INFO] Shared key established with ('127.0.0.1', 52522): 10000000000000000000000000000000
2025-01-02 12:33:28,356 - INFO - Processing command: light on
2025-01-02 12:33:32,747 - INFO - Processing command: thermostat get
2025-01-02 12:33:32,749 - ERROR - Error processing command: tuple indices must be integers or slices, not str
2025-01-02 12:33:32,749 - ERROR - [ERROR RESPONSE] Error: tuple indices must be integers or slices, not str
2025-01-02 12:33:37,620 - INFO - Processing command: thermostat set 78
2025-01-02 12:33:37,621 - ERROR - Error processing command: tuple indices must be integers or slices, not str
2025-01-02 12:33:37,621 - ERROR - [ERROR RESPONSE] Error: tuple indices must be integers or slices, not str
2025-01-02 12:35:27,434 - WARNING - [SERVER] Client ('127.0.0.1', 52522) disconnected abruptly.
2025-01-02 12:36:56,740 - DEBUG - Using proactor: IocpProactor
2025-01-02 12:36:56,742 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 12:37:00,977 - INFO - New connection from ('127.0.0.1', 52622)
2025-01-02 12:37:01,000 - INFO - [INFO] Shared key established with ('127.0.0.1', 52622): 01000000000000000000000000000000
2025-01-02 12:37:08,429 - INFO - Processing command: thermostat get
2025-01-02 12:37:08,430 - ERROR - Error processing command: tuple indices must be integers or slices, not str
2025-01-02 12:37:08,430 - ERROR - [ERROR RESPONSE] Error: tuple indices must be integers or slices, not str
2025-01-02 12:37:13,646 - INFO - Processing command: thermostat set
2025-01-02 12:37:13,646 - ERROR - [ERROR RESPONSE] Thermostat 'set' command must include a temperature value (e.g., 'thermostat set 25').
2025-01-02 12:37:13,646 - INFO - Validation error: RVooExjDcrgGiPl5YEEcWaOWkoG3i179i2wcGDJgmSb+groRi84cSEHd5Hrzk7SpPsZ5LujJlvUEq2p4cR+X9QgphaYb7qxHgWS+87cQd9AP/PrBfjxeDQcB6xkHscpLBrymB6NJAaMHc4kOgdi58g==
2025-01-02 12:37:17,932 - INFO - Processing command: light on
2025-01-02 12:37:19,812 - INFO - Processing command: fan n
2025-01-02 12:37:19,812 - ERROR - [ERROR RESPONSE] Invalid action 'n' for device 'fan'. Valid actions are: on, off, low, medium, high.
2025-01-02 12:37:19,814 - INFO - Validation error: sFmfpsiRviZ6JVGpKI9pxP6bemeUtjSBW2joMYvhAfowcN/FHk5XDuU0bQvtJpO/qj2/2UqqB/vYEdfHAflZMYtaIld6DYxdDmG0x3nm23weFPwAl9sLJbeWDajRBEkS8aaJCkIznMj3zDHW0JANDA==
2025-01-02 12:37:21,708 - INFO - Processing command: fan on
2025-01-02 12:37:24,078 - INFO - Processing command: fan off
2025-01-02 12:40:20,857 - DEBUG - Using proactor: IocpProactor
2025-01-02 12:40:20,859 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 12:40:23,829 - INFO - New connection from ('127.0.0.1', 52646)
2025-01-02 12:40:23,853 - INFO - [INFO] Shared key established with ('127.0.0.1', 52646): 01000000000000000000000000000000
2025-01-02 12:40:23,958 - INFO - [SERVER] Client ('127.0.0.1', 52646) disconnected.
2025-01-02 12:41:50,649 - DEBUG - Using proactor: IocpProactor
2025-01-02 12:41:50,652 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 12:41:55,919 - INFO - New connection from ('127.0.0.1', 52672)
2025-01-02 12:41:55,946 - INFO - [INFO] Shared key established with ('127.0.0.1', 52672): 01000000000000000000000000000000
2025-01-02 12:42:01,982 - INFO - Processing command: light on
2025-01-02 12:42:12,112 - INFO - Processing command: thermostat get
2025-01-02 12:42:12,112 - ERROR - Error processing command: tuple indices must be integers or slices, not str
2025-01-02 12:42:12,113 - ERROR - [ERROR RESPONSE] Error: tuple indices must be integers or slices, not str
2025-01-02 13:02:44,640 - DEBUG - Using proactor: IocpProactor
2025-01-02 13:02:44,646 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 13:02:48,489 - INFO - New connection from ('127.0.0.1', 52828)
2025-01-02 13:02:48,511 - INFO - [INFO] Shared key established with ('127.0.0.1', 52828): 10000000000000000000000000000000
2025-01-02 13:02:52,121 - INFO - Processing command: light on
2025-01-02 13:02:56,806 - INFO - Processing command: light off
2025-01-02 13:03:00,266 - INFO - Processing command: thermostat get
2025-01-02 13:03:11,285 - INFO - Processing command: thermostat set 45
2025-01-02 13:03:14,933 - INFO - Processing command: fan on
2025-01-02 13:03:17,196 - INFO - Processing command: fan off
2025-01-02 13:03:22,901 - INFO - Processing command: smart lock lock
2025-01-02 13:03:22,901 - ERROR - [ERROR RESPONSE] Unknown device 'smart'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2025-01-02 13:03:22,901 - INFO - Validation error: 9ebqA1HExicEbfUhU4QMiqOf5rK3aSER4C7StYVg69sQ+Wkvwyez1dafvSdMw0vNjvT05pRCcxz/ayTgVvmE7k1mT+fduU/cIpyiujDpP9H/a3EHbTKS4RWn/AT6ZYt4ohEp1RnPakdIud5BjlWdctq3yEZz+dlcknw2utc5Ric=
2025-01-02 13:03:32,330 - INFO - Processing command: speaker on
2025-01-02 13:03:35,473 - INFO - Processing command: speaker off
2025-01-02 13:03:43,263 - INFO - Processing command: camera on
2025-01-02 13:03:46,748 - INFO - Processing command: camera off
2025-01-02 13:03:53,921 - INFO - Processing command: smart lock locked
2025-01-02 13:03:53,921 - ERROR - [ERROR RESPONSE] Unknown device 'smart'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2025-01-02 13:03:53,922 - INFO - Validation error: sMkYrYpuVDJpBcv3bFWQzcuyRB8689KfTYpjhsgI5pZh6BdZNE3gsBufQz4d6uGYSY5FEw8sXI6bcMxzVBPLCBdsHR8cUIfrp3w1Q6zzCU3bKKpyyZLvG8U5qEuGxocMSpKUAxs0n0P0dzDGfMT1SYc/R0rh2ozIS3BEmEpgI6M=
2025-01-02 13:04:02,295 - INFO - Processing command: fan medium
2025-01-02 13:04:05,219 - INFO - Processing command: fan off
2025-01-02 13:08:14,396 - DEBUG - Using proactor: IocpProactor
2025-01-02 13:08:14,401 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 13:08:17,565 - INFO - New connection from ('127.0.0.1', 52875)
2025-01-02 13:08:17,595 - INFO - [INFO] Shared key established with ('127.0.0.1', 52875): 01000000000000000000000000000000
2025-01-02 13:08:20,914 - INFO - Processing command: light on
2025-01-02 13:08:25,818 - INFO - Processing command: thermostat get
2025-01-02 13:08:34,134 - INFO - Processing command: smart lock lock 5:16pm
2025-01-02 13:08:34,135 - ERROR - [ERROR RESPONSE] Unknown device 'smart'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2025-01-02 13:08:34,135 - INFO - Validation error: W19MameCee6rhkekuIJBtNrUutJl5Jlz811DvapHpDokq4KjU2RxE3ohqQ28w7pD9POsFPG/Jit33wwvOyrcI0rsnzBbeUqKeQY7dfLdl3E365341SwVixijNAxBqEWAHWTqHEYfXxLsukuPbGjH/hM8nhpw57SYmhI5UPGn2oE=
2025-01-02 13:08:40,436 - INFO - Processing command: smart lock locked
2025-01-02 13:08:40,436 - ERROR - [ERROR RESPONSE] Unknown device 'smart'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2025-01-02 13:08:40,437 - INFO - Validation error: Q+8c1+NqE0FDMOpCjoeouYxCdmx4jsAXPUywjH63uiu+Nk2VstTi2dVQBM3i+VyfWzfqgSwxiIzG15vie4NnvOiC1U3yLxqZzbfBJ3xUnunJFlegM2ksST5r2orBWv1Jh4O10Dpsg8pt7ra54eXVmutR7HLMTJJMOknl/P9fSd0=
2025-01-02 13:09:09,952 - INFO - Processing command: fan on
2025-01-02 13:09:14,094 - INFO - Processing command: smart lock locked
2025-01-02 13:09:14,094 - ERROR - [ERROR RESPONSE] Unknown device 'smart'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2025-01-02 13:09:14,095 - INFO - Validation error: dKvvdqf4hS/+u4kqYiPb9ty1OlJX+UZR2c8EL4Tls/84OP4AS8QaQqBrvyjwloeiQbQot8o8S9yt2ooVY/jx/y9boEiTRAQTI7XbpgDy0ktBKGQ9y2a0o7AeFiEBWNDgy0tKUJ+5tgAk/DqyXEAXeXoU58Wx/HzY/M3s/QGRhR8=
2025-01-02 13:12:53,665 - DEBUG - Using proactor: IocpProactor
2025-01-02 13:12:53,670 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 13:12:56,412 - INFO - New connection from ('127.0.0.1', 52912)
2025-01-02 13:12:56,444 - INFO - [INFO] Shared key established with ('127.0.0.1', 52912): 10000000000000000000000000000000
2025-01-02 13:12:59,922 - INFO - Processing command: light on
2025-01-02 13:13:05,206 - INFO - Processing command: smart lock locked
2025-01-02 13:13:18,566 - INFO - Processing command: smart lock lock 5:45 PM
2025-01-02 13:13:23,637 - INFO - Processing command: speaker on
2025-01-02 13:13:26,435 - INFO - Processing command: speaker off
2025-01-02 13:13:32,083 - INFO - Processing command: thermostat get
2025-01-02 13:13:37,775 - INFO - Processing command: thermostat set 56
2025-01-02 13:14:52,404 - DEBUG - Using proactor: IocpProactor
2025-01-02 13:14:52,407 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 13:14:55,578 - INFO - New connection from ('127.0.0.1', 52932)
2025-01-02 13:14:55,608 - INFO - [INFO] Shared key established with ('127.0.0.1', 52932): 04000000000000000000000000000000
2025-01-02 13:14:57,396 - INFO - Processing command: frefr
2025-01-02 13:14:57,396 - ERROR - [ERROR RESPONSE] Invalid command format. Must include a device and action (e.g., 'light on').
2025-01-02 13:14:57,396 - INFO - Validation error: 1Uelamic3YD48jOBWz06qMGPEKQnNn19yZ6OmsGhATd2XI9+C7a4WfUnnZ8Ss1p5v46CcY7VAjQp8CzcwENOMnhVAptufu5WYw0Iq9HOalKJdmDK9lnYgzoMgEfCqf7ZNeZ6gScfOCkArAbPdhp4Hw==
2025-01-02 13:15:02,865 - INFO - Processing command: fan onn
2025-01-02 13:15:02,865 - ERROR - [ERROR RESPONSE] Invalid action 'onn' for device 'fan'. Valid actions are: on, off, low, medium, high.
2025-01-02 13:15:02,865 - INFO - Validation error: omNoS3+fSxKecAfh4w3PhdQ5+njR3HyCQEMqSCrRqT0ljEK31gHCiDOoDnqj20j5eqA4vE2G9fq52cDDLLoXpTBslSOMNz/gFCdFNmWH0f9Zr3o5TlX9bWET22oZhyY/zsPAqGUPcghOWsgQulWIqw==
2025-01-02 13:31:23,077 - DEBUG - Using proactor: IocpProactor
2025-01-02 13:31:23,082 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 13:31:25,981 - INFO - New connection from ('127.0.0.1', 53246)
2025-01-02 13:31:26,011 - INFO - [INFO] Shared key established with ('127.0.0.1', 53246): 40000000000000000000000000000000
2025-01-02 13:31:29,602 - ERROR - [SERVER ERROR] Unexpected error: process_command() missing 1 required positional argument: 'writer'
2025-01-02 13:31:29,602 - ERROR - [ERROR RESPONSE] An unexpected server error occurred.
2025-01-02 13:56:33,228 - DEBUG - Using proactor: IocpProactor
2025-01-02 13:56:33,235 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 14:08:46,015 - INFO - New connection from ('127.0.0.1', 54009)
2025-01-02 14:08:46,034 - INFO - [INFO] Shared key established with ('127.0.0.1', 54009): 10000000000000000000000000000000
2025-01-02 14:08:49,584 - ERROR - [SERVER ERROR] Unexpected error: process_command() missing 1 required positional argument: 'writer'
2025-01-02 14:08:49,584 - ERROR - [ERROR RESPONSE] An unexpected server error occurred.
2025-01-02 14:13:04,883 - INFO - New connection from ('127.0.0.1', 54068)
2025-01-02 14:13:04,900 - INFO - [INFO] Shared key established with ('127.0.0.1', 54068): 40000000000000000000000000000000
2025-01-02 14:13:07,835 - ERROR - [SERVER ERROR] Unexpected error: process_command() missing 1 required positional argument: 'writer'
2025-01-02 14:13:07,835 - ERROR - [ERROR RESPONSE] An unexpected server error occurred.
2025-01-02 15:49:45,362 - DEBUG - Using proactor: IocpProactor
2025-01-02 15:49:45,365 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 15:49:47,897 - INFO - New connection from ('127.0.0.1', 54879)
2025-01-02 15:49:47,919 - INFO - [INFO] Shared key established with ('127.0.0.1', 54879): 01000000000000000000000000000000
2025-01-02 15:49:52,300 - INFO - Processing command: light on
2025-01-02 15:49:52,305 - ERROR - [ENCRYPTION ERROR] 'NoneType' object has no attribute 'encode'
2025-01-02 15:49:52,305 - ERROR - [SERVER ERROR] Unexpected error: 'NoneType' object has no attribute 'encode'
2025-01-02 15:49:52,305 - ERROR - [ERROR RESPONSE] An unexpected server error occurred.
2025-01-02 15:50:35,170 - INFO - New connection from ('127.0.0.1', 54897)
2025-01-02 15:50:35,186 - INFO - [INFO] Shared key established with ('127.0.0.1', 54897): 01000000000000000000000000000000
2025-01-02 15:50:39,358 - INFO - Processing command: light on
2025-01-02 15:50:39,359 - ERROR - [ENCRYPTION ERROR] 'NoneType' object has no attribute 'encode'
2025-01-02 15:50:39,359 - ERROR - [SERVER ERROR] Unexpected error: 'NoneType' object has no attribute 'encode'
2025-01-02 15:50:39,359 - ERROR - [ERROR RESPONSE] An unexpected server error occurred.
2025-01-02 15:55:27,661 - DEBUG - Using proactor: IocpProactor
2025-01-02 15:55:27,664 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 15:55:30,945 - INFO - New connection from ('127.0.0.1', 54944)
2025-01-02 15:55:30,961 - INFO - [INFO] Shared key established with ('127.0.0.1', 54944): 01000000000000000000000000000000
2025-01-02 15:55:33,797 - INFO - Processing command: light on
2025-01-02 15:55:37,705 - INFO - Processing command: thermostat get
2025-01-02 15:55:37,705 - ERROR - Error processing command: tuple indices must be integers or slices, not str
2025-01-02 15:55:37,705 - ERROR - [ERROR RESPONSE] Error: tuple indices must be integers or slices, not str
2025-01-02 15:55:55,833 - INFO - Processing command: hermostat get
2025-01-02 15:55:55,833 - ERROR - [ERROR RESPONSE] Unknown device 'hermostat'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2025-01-02 15:55:55,833 - INFO - Validation error: EQkMWMzy47+aM8QPEn3ZViGQ+QTM6NTIL3WhSJDF7RZ+m2ui1HvzNHXrHm1o3W3/Cjov3BsMVDW8TGgM6MJcyux7C6rt8ktDp3ecC15+vo/LqqZhQjMzcJ+xMrarSRLUVBWyZ+ATnN4w4WCTtJgnuj1s//a5OHLbm1Qw6K3cdr0=
2025-01-02 15:56:23,738 - INFO - Processing command: thermostat get
2025-01-02 15:56:23,738 - ERROR - Error processing command: tuple indices must be integers or slices, not str
2025-01-02 15:56:23,738 - ERROR - [ERROR RESPONSE] Error: tuple indices must be integers or slices, not str
2025-01-02 15:56:38,511 - INFO - Processing command: thermostat get
2025-01-02 15:56:38,511 - ERROR - Error processing command: tuple indices must be integers or slices, not str
2025-01-02 15:56:38,511 - ERROR - [ERROR RESPONSE] Error: tuple indices must be integers or slices, not str
2025-01-02 15:56:45,877 - INFO - Processing command: thermostat get
2025-01-02 15:56:45,877 - ERROR - Error processing command: tuple indices must be integers or slices, not str
2025-01-02 15:56:45,877 - ERROR - [ERROR RESPONSE] Error: tuple indices must be integers or slices, not str
2025-01-02 15:56:52,706 - INFO - Processing command: thermostat get
2025-01-02 15:56:52,707 - ERROR - Error processing command: tuple indices must be integers or slices, not str
2025-01-02 15:56:52,707 - ERROR - [ERROR RESPONSE] Error: tuple indices must be integers or slices, not str
2025-01-02 15:57:04,013 - INFO - Processing command: thermostat get
2025-01-02 15:57:04,013 - ERROR - Error processing command: tuple indices must be integers or slices, not str
2025-01-02 15:57:04,013 - ERROR - [ERROR RESPONSE] Error: tuple indices must be integers or slices, not str
2025-01-02 15:57:24,562 - INFO - Processing command: thermostat get
2025-01-02 15:57:24,562 - ERROR - Error processing command: tuple indices must be integers or slices, not str
2025-01-02 15:57:24,562 - ERROR - [ERROR RESPONSE] Error: tuple indices must be integers or slices, not str
2025-01-02 15:58:32,179 - DEBUG - Using proactor: IocpProactor
2025-01-02 15:58:32,181 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 15:58:35,186 - INFO - New connection from ('127.0.0.1', 54990)
2025-01-02 15:58:35,203 - INFO - [INFO] Shared key established with ('127.0.0.1', 54990): 10000000000000000000000000000000
2025-01-02 15:58:42,172 - INFO - Processing command: light on
2025-01-02 15:58:46,451 - INFO - Processing command: light off
2025-01-02 15:58:49,965 - INFO - Processing command: thermostat get
2025-01-02 15:58:55,057 - INFO - Processing command: thermostat set 67
2025-01-02 15:58:57,149 - INFO - Processing command: jjoi
2025-01-02 15:58:57,149 - ERROR - [ERROR RESPONSE] Invalid command format. Must include a device and action (e.g., 'light on').
2025-01-02 15:58:57,149 - INFO - Validation error: I0V+FGtRpJ8ywE6glb344Sa8pP35f+1ucNirkT0yXSfuq3YFitdRyh6yZjlPmCs7BErTl1fBAZUC+gaGxdND9/B6gLoiugvsFrQ4650XNXXi/5UQuscaK2Hyeb37TV/+o9u8MDMwIVwC2/Kq4y2/gw==
2025-01-02 15:58:59,801 - INFO - Processing command: fejjf&(*&
2025-01-02 15:58:59,801 - ERROR - [ERROR RESPONSE] Invalid command format. Must include a device and action (e.g., 'light on').
2025-01-02 15:58:59,801 - INFO - Validation error: 3vMflVNR7MGa3vB7ee+qlkImtfGqQO4st/5h55wyuW3oUldQsooqOCM7347A9OoSuR75y/Mf28YYHeCZnn+VbjQmuf0BkHSATe4HL4/FQouw4YgKMGL8qhjC9s27qSrvVCR4DISWe+dd9Vmp3KH5DA==
2025-01-02 15:59:02,744 - INFO - Processing command: fan of
2025-01-02 15:59:02,744 - ERROR - [ERROR RESPONSE] Invalid action 'of' for device 'fan'. Valid actions are: on, off, low, medium, high.
2025-01-02 15:59:02,744 - INFO - Validation error: p8ClF+ocO9BrYBu93kzR5XfGadaqETM0lyUMziiepp/Ze2vBckKdnF6fKI87Pl5miE1fn+W7jmUE0Jn+kcJA9SBi/YZmii9ywLMui+3w+f6CtE7XkeAUcTEVfb3MELbFxyETXt9N/4bR/uMLWK9fUA==
2025-01-02 15:59:05,762 - WARNING - [SERVER] Client ('127.0.0.1', 54990) disconnected abruptly.
2025-01-02 15:59:49,741 - DEBUG - Using proactor: IocpProactor
2025-01-02 15:59:49,744 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 15:59:52,322 - INFO - New connection from ('127.0.0.1', 55003)
2025-01-02 15:59:52,339 - INFO - [INFO] Shared key established with ('127.0.0.1', 55003): 80000000000000000000000000000000
2025-01-02 15:59:57,290 - INFO - Processing command: light on
2025-01-02 16:00:03,405 - INFO - Processing command: thermostat set 66
2025-01-02 16:00:06,561 - INFO - Processing command: jef*)(*
2025-01-02 16:00:06,561 - ERROR - [ERROR RESPONSE] Invalid command format. Must include a device and action (e.g., 'light on').
2025-01-02 16:00:06,561 - INFO - Validation error: YiwRPnSkiXgI2QK7l8L95u7RtTgPhb2nWIzyOfqmn1cFVr7Jz9k7okJXzq5eCHtIKXm7hSMT3py+FRO5+umOCzUoY81R4t4q9GMx8RTRCJ/3Nm1Qdk5BVp5WTAJRlyFfdX9fBznjvTwoTxx85y6Hcw==
2025-01-02 16:11:49,860 - DEBUG - Using proactor: IocpProactor
2025-01-02 16:11:49,861 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 16:12:05,912 - INFO - New connection from ('127.0.0.1', 55154)
2025-01-02 16:12:05,931 - INFO - [INFO] Shared key established with ('127.0.0.1', 55154): 04000000000000000000000000000000
2025-01-02 16:12:05,935 - ERROR - [DECRYPTION ERROR] 'utf-8' codec can't decode byte 0xfb in position 1: invalid start byte
2025-01-02 16:12:15,556 - INFO - New connection from ('127.0.0.1', 55158)
2025-01-02 16:12:15,574 - INFO - [INFO] Shared key established with ('127.0.0.1', 55158): 04000000000000000000000000000000
2025-01-02 16:12:15,577 - ERROR - [DECRYPTION ERROR] 'utf-8' codec can't decode byte 0x8b in position 2: invalid start byte
2025-01-02 16:18:38,057 - DEBUG - Using proactor: IocpProactor
2025-01-02 16:18:38,059 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 16:18:50,010 - INFO - New connection from ('127.0.0.1', 55226)
2025-01-02 16:18:50,028 - INFO - [INFO] Shared key established with ('127.0.0.1', 55226): 40000000000000000000000000000000
2025-01-02 16:18:50,031 - ERROR - [DECRYPTION ERROR] 'utf-8' codec can't decode byte 0xc7 in position 0: invalid continuation byte
2025-01-02 16:21:16,281 - DEBUG - Using proactor: IocpProactor
2025-01-02 16:21:16,283 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 16:21:24,440 - INFO - New connection from ('127.0.0.1', 55256)
2025-01-02 16:21:24,457 - INFO - [INFO] Shared key established with ('127.0.0.1', 55256): 80000000000000000000000000000000
2025-01-02 16:21:24,460 - ERROR - [DECRYPTION ERROR] 'utf-8' codec can't decode byte 0x9a in position 4: invalid start byte
2025-01-02 16:26:11,660 - DEBUG - Using proactor: IocpProactor
2025-01-02 16:26:11,661 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 16:26:14,653 - INFO - New connection from ('127.0.0.1', 55298)
2025-01-02 16:26:14,671 - INFO - [INFO] Shared key established with ('127.0.0.1', 55298): 10000000000000000000000000000000
2025-01-02 16:26:14,673 - ERROR - [DECRYPTION ERROR] 'utf-8' codec can't decode byte 0xe3 in position 0: invalid continuation byte
2025-01-02 16:29:12,821 - INFO - New connection from ('127.0.0.1', 55319)
2025-01-02 16:29:12,838 - INFO - [INFO] Shared key established with ('127.0.0.1', 55319): 04000000000000000000000000000000
2025-01-02 16:29:12,839 - ERROR - [DECRYPTION ERROR] 'utf-8' codec can't decode byte 0xbe in position 1: invalid start byte
2025-01-02 16:30:59,678 - DEBUG - Using proactor: IocpProactor
2025-01-02 16:30:59,680 - INFO - Server is running on 127.0.0.1:12345
2025-01-02 16:31:03,414 - INFO - New connection from ('127.0.0.1', 55339)
2025-01-02 16:31:03,432 - INFO - [INFO] Shared key established with ('127.0.0.1', 55339): 08000000000000000000000000000000
2025-01-02 16:31:03,435 - ERROR - [DECRYPTION ERROR] 'utf-8' codec can't decode byte 0xc4 in position 0: invalid continuation byte
2025-01-03 13:35:49,883 - DEBUG - Using proactor: IocpProactor
2025-01-03 13:35:49,889 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 13:35:49,967 - INFO - New connection from ('127.0.0.1', 63474)
2025-01-03 13:35:50,010 - INFO - [INFO] Shared key established with ('127.0.0.1', 63474): 40000000000000000000000000000000
2025-01-03 13:35:50,013 - ERROR - [DECRYPTION ERROR] 'utf-8' codec can't decode byte 0xe6 in position 0: invalid continuation byte
2025-01-03 13:43:44,341 - DEBUG - Using proactor: IocpProactor
2025-01-03 13:43:44,347 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 13:43:47,832 - INFO - New connection from ('127.0.0.1', 63598)
2025-01-03 13:43:47,859 - INFO - [INFO] Shared key established with ('127.0.0.1', 63598): 100000000000000000000000
2025-01-03 13:43:47,860 - ERROR - [DECRYPTION ERROR] Padding issue: Message too short for valid IV.
2025-01-03 13:43:47,860 - ERROR - [ENCRYPTION ERROR] Incorrect AES key length (12 bytes)
2025-01-03 13:43:47,860 - ERROR - [SERVER ERROR] Unexpected error: 'NoneType' object has no attribute 'encode'
2025-01-03 13:43:47,860 - ERROR - [ENCRYPTION ERROR] Incorrect AES key length (12 bytes)
2025-01-03 13:43:47,861 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=352>
Traceback (most recent call last):
  File "c:/Users/enosh/Desktop/Coursework 25'/Network Systems Development/Client-Server network/Server.py", line 332, in handle_client
    writer.write(response.encode("utf-8"))
                 ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/enosh/Desktop/Coursework 25'/Network Systems Development/Client-Server network/Server.py", line 392, in handle_client
    writer.write(response.encode("utf-8"))
                 ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode'
2025-01-03 13:55:48,096 - DEBUG - Using proactor: IocpProactor
2025-01-03 13:55:48,099 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 13:56:09,090 - INFO - New connection from ('127.0.0.1', 63761)
2025-01-03 13:56:09,118 - INFO - [INFO] Shared key established with ('127.0.0.1', 63761): 40000000000000000000000000000000
2025-01-03 13:56:09,120 - ERROR - [DECRYPTION ERROR] Padding issue: 'utf-8' codec can't decode byte 0xdd in position 4: invalid continuation byte
2025-01-03 13:58:45,180 - DEBUG - Using proactor: IocpProactor
2025-01-03 13:58:45,184 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 13:58:47,737 - INFO - New connection from ('127.0.0.1', 63792)
2025-01-03 13:58:47,762 - INFO - [INFO] Shared key established with ('127.0.0.1', 63792): 01000000000000000000000000000000
2025-01-03 13:58:47,762 - ERROR - [DECRYPTION ERROR] Padding issue: 'utf-8' codec can't decode byte 0xe5 in position 4: invalid continuation byte
2025-01-03 14:11:36,149 - INFO - New connection from ('127.0.0.1', 63991)
2025-01-03 14:11:36,172 - INFO - [INFO] Shared key established with ('127.0.0.1', 63991): 01000000000000000000000000000000
2025-01-03 14:11:36,180 - ERROR - [DECRYPTION ERROR] Padding issue: 'utf-8' codec can't decode byte 0xde in position 1: invalid continuation byte
2025-01-03 14:11:44,403 - DEBUG - Using proactor: IocpProactor
2025-01-03 14:11:44,406 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 14:11:47,677 - INFO - New connection from ('127.0.0.1', 64009)
2025-01-03 14:11:47,703 - INFO - [INFO] Shared key established with ('127.0.0.1', 64009): 01000000
2025-01-03 14:11:47,706 - ERROR - [DECRYPTION ERROR] Padding issue: Message too short for valid IV.
2025-01-03 14:11:47,706 - ERROR - [ENCRYPTION ERROR] Incorrect AES key length (4 bytes)
2025-01-03 14:11:47,706 - ERROR - [SERVER ERROR] Unexpected error: 'NoneType' object has no attribute 'encode'
2025-01-03 14:11:47,706 - ERROR - [ENCRYPTION ERROR] Incorrect AES key length (4 bytes)
2025-01-03 14:16:18,147 - DEBUG - Using proactor: IocpProactor
2025-01-03 14:16:18,150 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 14:16:21,405 - INFO - New connection from ('127.0.0.1', 64085)
2025-01-03 14:16:21,428 - INFO - [INFO] Shared key established with ('127.0.0.1', 64085): 80000000000000000000000000000000
2025-01-03 14:16:21,437 - ERROR - [DECRYPTION ERROR] Padding issue: 'utf-8' codec can't decode byte 0xe0 in position 1: invalid continuation byte
2025-01-03 14:24:08,866 - DEBUG - Using proactor: IocpProactor
2025-01-03 14:24:08,869 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 14:24:11,242 - INFO - New connection from ('127.0.0.1', 64206)
2025-01-03 14:24:11,260 - INFO - [INFO] Shared key established with ('127.0.0.1', 64206): 10000000000000000000000000000000
2025-01-03 14:24:11,342 - INFO - [SERVER] Client ('127.0.0.1', 64206) disconnected.
2025-01-03 14:28:32,004 - DEBUG - Using proactor: IocpProactor
2025-01-03 14:28:32,007 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 14:28:35,369 - INFO - New connection from ('127.0.0.1', 64295)
2025-01-03 14:28:35,462 - INFO - [SERVER] Client ('127.0.0.1', 64295) disconnected.
2025-01-03 14:52:44,244 - DEBUG - Using proactor: IocpProactor
2025-01-03 14:52:44,247 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 14:52:48,026 - INFO - New connection from ('127.0.0.1', 64663)
2025-01-03 14:52:48,045 - INFO - [INFO] Shared key established with ('127.0.0.1', 64663): 08000000000000000000000000000000
2025-01-03 14:52:52,599 - INFO - Processing command: light on
2025-01-03 14:52:54,835 - INFO - Processing command: light off
2025-01-03 14:52:58,516 - INFO - Processing command: thermostat get
2025-01-03 14:53:05,265 - INFO - Processing command: thermostat set 569
2025-01-03 14:53:14,420 - INFO - Processing command: smart lock lock
2025-01-03 14:53:18,978 - INFO - Processing command: smart lock locked
2025-01-03 15:07:50,832 - DEBUG - Using proactor: IocpProactor
2025-01-03 15:07:50,834 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 15:07:54,174 - INFO - New connection from ('127.0.0.1', 64956)
2025-01-03 15:07:54,191 - INFO - [INFO] Shared key established with ('127.0.0.1', 64956): 40000000000000000000000000000000
2025-01-03 15:07:54,193 - ERROR - [SERVER ERROR] Unexpected error: decrypt_message() missing 1 required positional argument: 'expected_packet_id'
2025-01-03 15:07:54,193 - ERROR - [ERROR RESPONSE] An unexpected server error occurred.
2025-01-03 15:07:54,193 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=584 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "c:/Users/enosh/Desktop/Coursework 25'/Network Systems Development/Client-Server network/Server.py", line 307, in handle_client
    auth_message = decrypt_message(encrypted_auth_message.decode("utf-8"), shared_key)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: decrypt_message() missing 1 required positional argument: 'expected_packet_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/enosh/Desktop/Coursework 25'/Network Systems Development/Client-Server network/Server.py", line 369, in handle_client
    response = create_error_response("An unexpected server error occurred.")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:/Users/enosh/Desktop/Coursework 25'/Network Systems Development/Client-Server network/Server.py", line 129, in create_error_response
    return encrypt_message(f"[ERROR] {error_message}", SECRET_KEY)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: encrypt_message() missing 1 required positional argument: 'packet_id'
2025-01-03 15:16:49,162 - DEBUG - Using proactor: IocpProactor
2025-01-03 15:16:49,164 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 15:16:52,636 - INFO - New connection from ('127.0.0.1', 65131)
2025-01-03 15:16:52,654 - INFO - [INFO] Shared key established with ('127.0.0.1', 65131): 40000000000000000000000000000000
2025-01-03 15:16:52,657 - ERROR - [DECRYPTION ERROR] Packet ID mismatch. Possible replay attack detected.
2025-01-03 15:17:08,918 - DEBUG - Using proactor: IocpProactor
2025-01-03 15:17:08,920 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 15:17:12,629 - INFO - New connection from ('127.0.0.1', 65140)
2025-01-03 15:17:12,646 - INFO - [INFO] Shared key established with ('127.0.0.1', 65140): 20000000000000000000000000000000
2025-01-03 15:17:12,651 - ERROR - [DECRYPTION ERROR] Packet ID mismatch. Possible replay attack detected.
2025-01-03 15:21:42,370 - DEBUG - Using proactor: IocpProactor
2025-01-03 15:21:42,372 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 15:21:49,408 - INFO - New connection from ('127.0.0.1', 65226)
2025-01-03 15:21:49,426 - INFO - [INFO] Shared key established with ('127.0.0.1', 65226): 10000000000000000000000000
2025-01-03 15:21:49,426 - ERROR - [DECRYPTION ERROR] Message too short for valid IV.
2025-01-03 15:21:49,426 - ERROR - [ENCRYPTION ERROR] Incorrect AES key length (13 bytes)
2025-01-03 15:21:49,426 - ERROR - [SERVER ERROR] Unexpected error: 'NoneType' object has no attribute 'encode'
2025-01-03 15:21:49,426 - ERROR - [ENCRYPTION ERROR] Incorrect AES key length (13 bytes)
2025-01-03 15:21:49,426 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=520>
Traceback (most recent call last):
  File "c:/Users/enosh/Desktop/Coursework 25'/Network Systems Development/Client-Server network/Server.py", line 312, in handle_client
    writer.write(response.encode("utf-8"))
                 ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/enosh/Desktop/Coursework 25'/Network Systems Development/Client-Server network/Server.py", line 377, in handle_client
    writer.write(response.encode("utf-8"))
                 ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode'
2025-01-03 15:26:45,656 - DEBUG - Using proactor: IocpProactor
2025-01-03 15:26:45,659 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 15:26:48,240 - INFO - New connection from ('127.0.0.1', 65284)
2025-01-03 15:26:48,258 - INFO - [INFO] Shared key established with ('127.0.0.1', 65284): 80000000000000000000000000000000
2025-01-03 15:26:48,261 - ERROR - [DECRYPTION ERROR] Packet ID mismatch. Possible replay attack detected.
2025-01-03 15:33:03,453 - DEBUG - Using proactor: IocpProactor
2025-01-03 15:33:03,455 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 15:33:07,548 - INFO - New connection from ('127.0.0.1', 65416)
2025-01-03 15:33:07,565 - INFO - [INFO] Shared key established with ('127.0.0.1', 65416): 10000000000000000000000000000000
2025-01-03 15:33:07,568 - ERROR - [DECRYPTION ERROR] Packet ID mismatch. Possible replay attack detected.
2025-01-03 15:40:28,888 - INFO - New connection from ('127.0.0.1', 49205)
2025-01-03 15:40:28,905 - INFO - [INFO] Shared key established with ('127.0.0.1', 49205): 02000000000000000000000000000000
2025-01-03 15:40:28,907 - ERROR - [DECRYPTION ERROR] Packet ID mismatch. Possible replay attack detected.
2025-01-03 15:40:35,497 - DEBUG - Using proactor: IocpProactor
2025-01-03 15:40:35,498 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 15:40:39,420 - INFO - New connection from ('127.0.0.1', 49212)
2025-01-03 15:40:39,438 - INFO - [INFO] Shared key established with ('127.0.0.1', 49212): 10000000000000000000000000000000
2025-01-03 15:40:39,443 - ERROR - [DECRYPTION ERROR] Packet ID mismatch. Possible replay attack detected.
2025-01-03 16:06:00,235 - DEBUG - Using proactor: IocpProactor
2025-01-03 16:06:00,237 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 16:06:03,106 - INFO - New connection from ('127.0.0.1', 50244)
2025-01-03 16:06:03,122 - INFO - [INFO] Shared key established with ('127.0.0.1', 50244): 40000000000000000000000000000000
2025-01-03 16:06:03,125 - ERROR - [SERVER] Invalid packet format.
2025-01-03 16:06:25,156 - DEBUG - Using proactor: IocpProactor
2025-01-03 16:06:25,158 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 16:06:28,092 - INFO - New connection from ('127.0.0.1', 50251)
2025-01-03 16:06:28,110 - INFO - [INFO] Shared key established with ('127.0.0.1', 50251): 02000000000000000000000000000000
2025-01-03 16:06:28,111 - ERROR - [SERVER] Invalid packet format.
2025-01-03 16:07:38,984 - DEBUG - Using proactor: IocpProactor
2025-01-03 16:07:38,986 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 16:07:42,258 - INFO - New connection from ('127.0.0.1', 50298)
2025-01-03 16:07:42,275 - INFO - [INFO] Shared key established with ('127.0.0.1', 50298): 40000000000000000000000000000000
2025-01-03 16:07:42,277 - ERROR - [SERVER] Invalid packet format.
2025-01-03 20:01:55,057 - DEBUG - Using proactor: IocpProactor
2025-01-03 20:01:55,060 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 20:01:55,193 - INFO - New connection from ('127.0.0.1', 55723)
2025-01-03 20:01:55,214 - INFO - [INFO] Shared key established with ('127.0.0.1', 55723): 80000000000000000000000000000000
2025-01-03 20:01:55,216 - ERROR - [SERVER] Invalid packet format.
2025-01-03 20:01:58,538 - INFO - New connection from ('127.0.0.1', 55731)
2025-01-03 20:01:58,556 - INFO - [INFO] Shared key established with ('127.0.0.1', 55731): 10000000000000000000000000000000
2025-01-03 20:01:58,558 - ERROR - [SERVER] Invalid packet format.
2025-01-03 20:03:40,090 - DEBUG - Using proactor: IocpProactor
2025-01-03 20:03:40,091 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 20:03:43,420 - INFO - New connection from ('127.0.0.1', 55790)
2025-01-03 20:03:43,437 - INFO - [INFO] Shared key established with ('127.0.0.1', 55790): 08000000000000000000000000000000
2025-01-03 20:03:43,439 - INFO - [SERVER] Received packet ID for auth: 6f543fe5-9ed1-4d90-a725-5ce92ad7cd91
2025-01-03 20:03:51,732 - INFO - [SERVER] Received packet ID: 6c8a17e9-6fcc-424d-88af-aff3cbc4de15
2025-01-03 20:03:51,732 - INFO - Processing command: light on
2025-01-03 20:04:22,767 - INFO - [SERVER] Received packet ID: 6e31dcd3-091e-4e9f-a93a-6a0ccebf9fd2
2025-01-03 20:04:22,767 - INFO - Processing command: thermostat get
2025-01-03 20:04:32,960 - INFO - [SERVER] Received packet ID: 7aaa11ea-fc80-4e88-99c3-0da62f1fe7e0
2025-01-03 20:04:32,960 - INFO - Processing command: thermostat set 45
2025-01-03 20:06:18,691 - DEBUG - Using proactor: IocpProactor
2025-01-03 20:06:18,695 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 20:06:29,085 - INFO - New connection from ('127.0.0.1', 55847)
2025-01-03 20:06:29,105 - INFO - [INFO] Shared key established with ('127.0.0.1', 55847): 01000000000000000000000000000000
2025-01-03 20:06:29,108 - INFO - [SERVER] Received packet ID for auth: a1e2d66d-3edc-48ae-9e38-e97b67ecec76
2025-01-03 20:08:33,706 - DEBUG - Using proactor: IocpProactor
2025-01-03 20:08:33,708 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 20:08:37,280 - INFO - New connection from ('127.0.0.1', 55898)
2025-01-03 20:08:37,298 - INFO - [INFO] Shared key established with ('127.0.0.1', 55898): 20000000000000000000000000000000
2025-01-03 20:08:37,299 - INFO - [SERVER] Received packet ID for auth: 6378a8bb-b8b3-4656-b1c8-acd9ba26e573
2025-01-03 20:08:49,645 - INFO - [SERVER] Received packet ID: 923cd61e-11d0-46c2-8eb8-58e1fe9cbad7
2025-01-03 20:08:49,645 - INFO - Processing command: light on
2025-01-03 20:09:08,937 - INFO - [SERVER] Received packet ID: 7925d17a-aa76-44c0-a9c7-3cbfb507398a
2025-01-03 20:09:08,937 - INFO - Processing command: light off
2025-01-03 20:09:19,057 - INFO - [SERVER] Received packet ID: babed222-4a98-453a-9e33-38eb1542b083
2025-01-03 20:09:19,057 - INFO - Processing command: thermostat get
2025-01-03 20:09:27,416 - INFO - [SERVER] Received packet ID: 1d401c15-40d4-4d7f-ac02-12a0611d189e
2025-01-03 20:09:27,417 - INFO - Processing command: thermostat set 56
2025-01-03 20:09:36,351 - INFO - [SERVER] Received packet ID: 51f0e502-597f-4d6b-bdbd-c686a56ed247
2025-01-03 20:09:36,352 - INFO - Processing command: fan off
2025-01-03 20:09:39,489 - INFO - [SERVER] Received packet ID: d3b983ab-7b5e-4b1b-b6eb-97a9b652813f
2025-01-03 20:09:39,489 - INFO - Processing command: fan low
2025-01-03 20:09:51,847 - INFO - [SERVER] Received packet ID: 99b12a6d-b663-46a2-b63f-a90230d3b83f
2025-01-03 20:09:51,848 - INFO - Processing command: fan of
2025-01-03 20:09:51,848 - ERROR - [ERROR RESPONSE] Invalid action 'of' for device 'fan'. Valid actions are: on, off, low, medium, high.
2025-01-03 20:09:51,848 - ERROR - [COMMAND ERROR] encrypt_message() missing 1 required positional argument: 'packet_id'
2025-01-03 20:10:03,740 - INFO - [SERVER] Received packet ID: 7dad4366-2129-40ee-a175-529c332b61a0
2025-01-03 20:10:03,741 - INFO - Processing command: smart lock lock
2025-01-03 20:10:08,222 - INFO - [SERVER] Received packet ID: 309b6e71-0686-4418-a1fd-df0aab241a12
2025-01-03 20:10:08,222 - INFO - Processing command: smart lock locked
2025-01-03 20:10:11,653 - INFO - [SERVER] Received packet ID: b058c4e0-d2f4-4046-8b6a-6da9eaa18b15
2025-01-03 20:10:11,653 - INFO - Processing command: camera on
2025-01-03 20:10:23,579 - INFO - [SERVER] Received packet ID: 95ca8a9d-ce97-4e9a-b228-6ed336dad607
2025-01-03 20:10:23,579 - INFO - Processing command: speaker on
2025-01-03 20:10:29,544 - INFO - [SERVER] Received packet ID: 4816a0bf-51e3-4f55-a897-30e3695e4ecd
2025-01-03 20:10:29,544 - INFO - Processing command: light on
2025-01-03 20:10:31,415 - INFO - [SERVER] Received packet ID: f5e0a4cf-f2ec-44ee-a022-1ea8f5b99923
2025-01-03 20:10:31,415 - INFO - Processing command: fan on
2025-01-03 20:10:33,622 - INFO - [SERVER] Received packet ID: 72b51f07-2946-4c78-a85e-19a048c22d5f
2025-01-03 20:10:33,622 - INFO - Processing command: ligh of
2025-01-03 20:10:33,622 - ERROR - [ERROR RESPONSE] Unknown device 'ligh'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2025-01-03 20:10:33,622 - ERROR - [COMMAND ERROR] encrypt_message() missing 1 required positional argument: 'packet_id'
2025-01-03 20:13:26,449 - DEBUG - Using proactor: IocpProactor
2025-01-03 20:13:26,450 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 20:13:33,188 - INFO - New connection from ('127.0.0.1', 56041)
2025-01-03 20:13:33,206 - INFO - [INFO] Shared key established with ('127.0.0.1', 56041): 80000000000000000000000000000000
2025-01-03 20:13:33,208 - INFO - [SERVER] Received packet ID for auth: 5a936327-3b83-478f-8d43-8ca3315f0739
2025-01-03 20:13:37,615 - INFO - [SERVER] Received packet ID: 245b8649-bbee-4eae-a43f-61ff89e239b6
2025-01-03 20:13:37,615 - INFO - Processing command: light on
2025-01-03 20:13:40,499 - INFO - [SERVER] Received packet ID: ae9587e1-f36d-4882-bed4-009bad7a5936
2025-01-03 20:13:40,499 - INFO - Processing command: ligh of
2025-01-03 20:13:40,499 - ERROR - [ERROR RESPONSE] Unknown device 'ligh'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2025-01-03 20:13:40,499 - ERROR - [COMMAND ERROR] encrypt_message() missing 1 required positional argument: 'packet_id'
2025-01-03 20:21:12,389 - DEBUG - Using proactor: IocpProactor
2025-01-03 20:21:12,395 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 20:21:15,012 - INFO - New connection from ('127.0.0.1', 56173)
2025-01-03 20:21:15,042 - INFO - [INFO] Shared key established with ('127.0.0.1', 56173): 01000000000000000000000000000000
2025-01-03 20:21:15,047 - INFO - [SERVER] Received packet ID for auth: 071c6793-c274-4367-b203-9c2922e001ee
2025-01-03 20:21:18,417 - INFO - [SERVER] Received packet ID: b9be875d-e60f-4400-b313-ae74a3fea4db
2025-01-03 20:21:18,417 - INFO - Processing command: light on
2025-01-03 20:21:20,733 - INFO - [SERVER] Received packet ID: 67172e43-58be-4451-b8a1-40d5a48ce1f2
2025-01-03 20:21:20,734 - INFO - Processing command: light of
2025-01-03 20:21:20,734 - ERROR - [ERROR RESPONSE] Invalid action 'of' for device 'light'. Valid actions are: on, off.
2025-01-03 20:21:20,734 - ERROR - [COMMAND ERROR] encrypt_message() missing 1 required positional argument: 'packet_id'
2025-01-03 20:30:45,852 - DEBUG - Using proactor: IocpProactor
2025-01-03 20:30:45,855 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 20:30:49,328 - INFO - New connection from ('127.0.0.1', 56634)
2025-01-03 20:30:49,357 - INFO - [INFO] Shared key established with ('127.0.0.1', 56634): 10000000
2025-01-03 20:30:49,360 - ERROR - [SERVER] Invalid packet format.
2025-01-03 20:33:14,089 - DEBUG - Using proactor: IocpProactor
2025-01-03 20:33:14,092 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 20:33:17,360 - INFO - New connection from ('127.0.0.1', 56658)
2025-01-03 20:33:17,392 - INFO - [INFO] Shared key established with ('127.0.0.1', 56658): 01000000000000000000000000000000
2025-01-03 20:33:17,393 - INFO - [SERVER] Received packet ID for auth: fec0618b-5863-4b1e-8280-a987b901e9f0
2025-01-03 20:33:23,642 - INFO - [SERVER] Received packet ID: 4c4b6a9a-fde6-4e24-ac58-eda1617bfaa1
2025-01-03 20:33:23,643 - INFO - Processing command: light on
2025-01-03 20:33:31,678 - INFO - [SERVER] Received packet ID: b11f5ead-9bac-4bbf-a8ac-263625b72248
2025-01-03 20:33:31,679 - INFO - Processing command: light off
2025-01-03 20:33:35,600 - INFO - [SERVER] Received packet ID: 8d3128d3-d511-4389-bcfd-b6b7e14daacf
2025-01-03 20:33:35,601 - INFO - Processing command: ligh of
2025-01-03 20:33:35,601 - ERROR - [COMMAND ERROR] create_error_response() missing 2 required positional arguments: 'key' and 'packet_id'
2025-01-03 20:43:00,873 - DEBUG - Using proactor: IocpProactor
2025-01-03 20:43:00,876 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 20:43:05,062 - INFO - New connection from ('127.0.0.1', 56745)
2025-01-03 20:43:05,088 - INFO - [INFO] Shared key established with ('127.0.0.1', 56745): 01
2025-01-03 20:43:05,088 - ERROR - [SERVER] Invalid packet format.
2025-01-03 20:43:13,522 - DEBUG - Using proactor: IocpProactor
2025-01-03 20:43:13,524 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 20:43:16,335 - INFO - New connection from ('127.0.0.1', 56752)
2025-01-03 20:43:16,358 - INFO - [INFO] Shared key established with ('127.0.0.1', 56752): 01000000000000000000000000000000
2025-01-03 20:43:16,365 - INFO - [SERVER] Received packet ID for auth: 226e5396-6c26-4da6-9d77-cbb4762e7bbe
2025-01-03 20:43:19,919 - INFO - [SERVER] Received packet ID: 064870df-ab89-4fb4-83d7-22150c07ac43
2025-01-03 20:43:19,920 - INFO - Processing command: light on
2025-01-03 20:43:24,629 - INFO - [SERVER] Received packet ID: ded97eb9-94b5-4079-abf2-b82500f4df79
2025-01-03 20:43:24,629 - INFO - Processing command: light off
2025-01-03 20:43:31,189 - INFO - [SERVER] Received packet ID: e8fd31fc-cfb4-48ee-bfd7-ac23519d568c
2025-01-03 20:43:31,189 - INFO - Processing command: ligh of
2025-01-03 20:43:31,191 - ERROR - [COMMAND ERROR] create_error_response() missing 2 required positional arguments: 'key' and 'packet_id'
2025-01-03 20:43:49,137 - INFO - [SERVER] Received packet ID: 64664dcf-d599-4d30-93bb-a8c13d7feba1
2025-01-03 20:43:49,137 - INFO - Processing command: light on
2025-01-03 20:43:53,036 - INFO - [SERVER] Received packet ID: fc0a4b12-d32f-4cf8-af15-50795306ba2f
2025-01-03 20:43:53,036 - INFO - Processing command: light of
2025-01-03 20:43:53,036 - ERROR - [COMMAND ERROR] create_error_response() missing 2 required positional arguments: 'key' and 'packet_id'
2025-01-03 21:01:44,998 - DEBUG - Using proactor: IocpProactor
2025-01-03 21:01:45,000 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 21:01:49,151 - INFO - New connection from ('127.0.0.1', 56942)
2025-01-03 21:01:49,174 - INFO - [INFO] Shared key established with ('127.0.0.1', 56942): 10000000000000000000000000000000
2025-01-03 21:01:49,178 - INFO - [SERVER] Received packet ID for auth: 941c9afe-7d5c-4dde-a9ee-2fa842b5513a
2025-01-03 21:01:53,007 - INFO - [SERVER] Received packet ID: 97bb58d9-9b4f-42e8-9962-90aea59e130e
2025-01-03 21:01:53,007 - ERROR - [SERVER ERROR] Unexpected error: process_command() missing 1 required positional argument: 'packet_id'
2025-01-03 21:04:30,499 - DEBUG - Using proactor: IocpProactor
2025-01-03 21:04:30,504 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 21:04:33,996 - INFO - New connection from ('127.0.0.1', 56981)
2025-01-03 21:04:34,021 - INFO - [INFO] Shared key established with ('127.0.0.1', 56981): 01000000000000000000000000000000
2025-01-03 21:04:34,028 - INFO - [SERVER] Received packet ID for auth: 1dadabaa-bbbf-46a4-b985-54357454021b
2025-01-03 21:04:37,153 - INFO - [SERVER] Received packet ID: 003fa87f-ff81-44db-b613-35a16e174a46
2025-01-03 21:04:37,153 - ERROR - [SERVER ERROR] Unexpected error: process_command() missing 1 required positional argument: 'packet_id'
2025-01-03 21:07:15,272 - DEBUG - Using proactor: IocpProactor
2025-01-03 21:07:15,278 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 21:07:18,036 - INFO - New connection from ('127.0.0.1', 57011)
2025-01-03 21:07:18,068 - INFO - [INFO] Shared key established with ('127.0.0.1', 57011): 04000000000000000000000000000000
2025-01-03 21:07:18,068 - INFO - [SERVER] Received packet ID for auth: 4db999f8-7206-42fb-b668-73d01ef1ad03
2025-01-03 21:07:22,710 - INFO - [SERVER] Received packet ID: 663cc0ec-bd8c-49ed-b1b6-667fad00ed1f
2025-01-03 21:07:22,710 - INFO - Processing command: light on
2025-01-03 21:07:29,322 - INFO - [SERVER] Received packet ID: f868f368-34bd-4242-a4a0-9d122b9c3550
2025-01-03 21:07:29,323 - INFO - Processing command: light off
2025-01-03 21:07:32,591 - INFO - [SERVER] Received packet ID: 54e42e9e-3164-40a8-90cb-951456f76ff9
2025-01-03 21:07:32,591 - INFO - Processing command: ligh ty
2025-01-03 21:07:32,591 - INFO - Validation error: G6c0hT2BmgzxwpGp6mpPpfx4JMaQmh+gnO8G63nNq4ZLhjJByWtFaEBMqF5BHqHTZ/CpN4nm+PaK7ue88y84jYbpKsm6n77R7ydPEsVP7SupTUDlvvHgHQA0XPQjrgHSpEFNMvpcZgCVsvjw6JGsU7q3BrMSsACCb+PmYNv97CXGKkThyEL6s3H7htB1KdyRHDImsjV+/gzQRwUhHyHpLA==
2025-01-03 21:07:33,606 - INFO - [SERVER] Received packet ID: 5052a13c-6317-4a37-bff9-b9e438e04e04
2025-01-03 21:07:33,606 - INFO - Processing command: t
2025-01-03 21:07:33,606 - INFO - Validation error: 9kSVvDIG0i+c5ldveorbmv4p01fjJSNQQqnMlrf5kopuD5o9KhG9/EtH5MH9lfT4r81YJh5Cv4bVH4Xpr4w0Z//ijBKzPwcRnH502k7vYU1gjWXrkOC3n15ABIsAJM9Gg/hWOM107dol3D0g3lAFFSNpKvsnUlNgfrlaLJzc4aTRyK9Hxern6HicdQYa5d65
2025-01-03 21:11:22,681 - DEBUG - Using proactor: IocpProactor
2025-01-03 21:11:22,685 - INFO - Server is running on 127.0.0.1:12345
2025-01-03 21:11:25,042 - INFO - New connection from ('127.0.0.1', 57107)
2025-01-03 21:11:25,072 - INFO - [INFO] Shared key established with ('127.0.0.1', 57107): 01000000000000000000000000000000
2025-01-03 21:11:25,076 - INFO - [SERVER] Received packet ID for auth: 92754b40-a826-4367-97cf-3e10da7c3ca9
2025-01-03 21:11:28,978 - INFO - [SERVER] Received packet ID: 2e3521c9-d6be-4015-a86e-1e4f354f37dd
2025-01-03 21:11:28,978 - INFO - Processing command: light on
2025-01-03 21:11:32,317 - INFO - [SERVER] Received packet ID: 45be3bde-600b-4591-8e2d-0870d0589b6b
2025-01-03 21:11:32,318 - INFO - Processing command: ligh tty
2025-01-03 21:11:32,318 - INFO - Validation error: UYn3+hVMnLxiCp5Hhf63PWkixSxqkfMdUzj8TLIN5+/gzLzGxO8ZfRwmJP49RZR16OJnfWQHhypu/Hlnc7XsJYPxl7tWENWNxFRHdHVJK3Bv9tkQiruFDJwmAijj6D0OrndIS5uFS0KQLXYGWEhLJWuRDdwvOm81Ur7dJ0JV/MpCyagTtaoTk2a1a/4lDiXVNcybWOtZ8O8OyZ9NjW4KXw==
2025-01-03 21:24:59,534 - WARNING - [SERVER] Client ('127.0.0.1', 57107) disconnected abruptly.
2025-01-04 13:59:13,086 - DEBUG - Using proactor: IocpProactor
2025-01-04 13:59:13,091 - INFO - Server is running on 127.0.0.1:12345
2025-01-04 13:59:13,281 - INFO - New connection from ('127.0.0.1', 65410)
2025-01-04 13:59:13,312 - INFO - [INFO] Shared key established with ('127.0.0.1', 65410): 40000000000000000000000000000000
2025-01-04 13:59:13,315 - INFO - [SERVER] Received packet ID for auth: c93af697-628b-496a-b412-8a37ea05768f
2025-01-04 13:59:21,961 - INFO - [SERVER] Received packet ID: 91c50adc-9382-4e9b-8ba8-292c0213fac8
2025-01-04 13:59:21,961 - INFO - Processing command: light on
2025-01-04 13:59:25,291 - INFO - [SERVER] Received packet ID: bf1c8c78-104f-48b3-be22-f39b00a7fab2
2025-01-04 13:59:25,292 - INFO - Processing command: light off
2025-01-04 14:00:18,029 - DEBUG - Using proactor: IocpProactor
2025-01-04 14:00:18,031 - INFO - Server is running on 127.0.0.1:12345
2025-01-04 14:00:24,651 - INFO - New connection from ('127.0.0.1', 65432)
2025-01-04 14:00:24,681 - INFO - [INFO] Shared key established with ('127.0.0.1', 65432): 08000000000000000000000000000000
2025-01-04 14:00:24,685 - INFO - [SERVER] Received packet ID for auth: 323a0098-152b-412e-af65-9df49772bdac
2025-01-04 14:00:28,870 - INFO - [SERVER] Received packet ID: f4f20c89-f9c7-4943-bac6-154ed568338c
2025-01-04 14:00:28,870 - INFO - Processing command: light on
2025-01-04 14:00:31,731 - INFO - [SERVER] Received packet ID: e8823ef1-f923-48b0-b739-1668c5768cc0
2025-01-04 14:00:31,731 - INFO - Processing command: light off
2025-01-04 14:00:37,646 - INFO - [SERVER] Received packet ID: f3578d16-bfb4-498d-a797-8e297b835e6e
2025-01-04 14:00:37,646 - INFO - Processing command: thermostat get
2025-01-04 14:00:39,368 - INFO - [SERVER] Received packet ID: e87c0946-21c4-46fc-813b-064af7e5f217
2025-01-04 14:00:39,369 - INFO - Processing command: 
2025-01-04 14:00:39,369 - ERROR - [ERROR RESPONSE] Invalid command format. Must include a device and action (e.g., 'light on').
2025-01-04 14:00:39,369 - ERROR - [COMMAND ERROR] encrypt_message() missing 1 required positional argument: 'packet_id'
2025-01-04 14:00:43,974 - INFO - [SERVER] Received packet ID: 8f68b986-7c40-491e-b0e8-9f0f255d6739
2025-01-04 14:00:43,975 - INFO - Processing command: light of
2025-01-04 14:00:43,975 - ERROR - [ERROR RESPONSE] Invalid action 'of' for device 'light'. Valid actions are: on, off.
2025-01-04 14:00:43,975 - ERROR - [COMMAND ERROR] encrypt_message() missing 1 required positional argument: 'packet_id'
2025-01-04 14:02:06,572 - DEBUG - Using proactor: IocpProactor
2025-01-04 14:02:06,575 - INFO - Server is running on 127.0.0.1:12345
2025-01-04 14:02:11,163 - INFO - New connection from ('127.0.0.1', 65476)
2025-01-04 14:02:11,191 - INFO - [INFO] Shared key established with ('127.0.0.1', 65476): 01000000000000000000000000000000
2025-01-04 14:02:11,195 - INFO - [SERVER] Received packet ID for auth: 93deedc8-f513-4f4c-a134-9347908b78a3
2025-01-04 15:56:02,863 - DEBUG - Using proactor: IocpProactor
2025-01-04 15:56:02,864 - INFO - Server is running on 127.0.0.1:12345
2025-01-04 15:56:03,178 - INFO - New connection from ('127.0.0.1', 51287)
2025-01-04 15:56:03,194 - INFO - [INFO] Shared key established: 01000000000000000000000000000000
2025-01-04 15:56:34,255 - DEBUG - Using proactor: IocpProactor
2025-01-04 15:56:34,257 - INFO - Server is running on 127.0.0.1:12345
2025-01-04 16:22:55,235 - INFO - New connection from ('127.0.0.1', 51605)
2025-01-04 16:22:55,252 - INFO - [INFO] Shared key established: 01000000000000000000000000000000
2025-01-04 16:23:23,829 - DEBUG - Using proactor: IocpProactor
2025-01-04 16:23:23,831 - INFO - Server is running on 127.0.0.1:12345
2025-01-04 16:23:27,604 - INFO - New connection from ('127.0.0.1', 51623)
2025-01-04 16:23:27,621 - INFO - [INFO] Shared key established: 10000000000000000000000000000000
2025-01-04 16:23:37,166 - INFO - Processing command: light on
2025-01-04 16:23:40,059 - INFO - Processing command: light off
2025-01-04 16:24:34,714 - DEBUG - Using proactor: IocpProactor
2025-01-04 16:24:34,715 - INFO - Server is running on 127.0.0.1:12345
2025-01-04 16:24:37,891 - INFO - New connection from ('127.0.0.1', 51652)
2025-01-04 16:24:37,909 - INFO - [INFO] Shared key established: 01000000000000000000000000000000
2025-01-04 16:25:40,596 - DEBUG - Using proactor: IocpProactor
2025-01-04 16:25:40,599 - INFO - Server is running on 127.0.0.1:12345
2025-01-04 16:25:43,444 - INFO - New connection from ('127.0.0.1', 51676)
2025-01-04 16:25:43,461 - INFO - [INFO] Shared key established with ('127.0.0.1', 51676): 01000000000000000000000000000000
2025-01-04 16:25:43,463 - INFO - [SERVER] Received packet ID for auth: e8a4aca8-eb6b-4bbc-8655-89f3ed7fb891
2025-01-04 16:25:50,016 - INFO - [SERVER] Received packet ID: ff6c4f34-d50c-4a4e-b49c-89c1f52ef184
2025-01-04 16:25:50,018 - INFO - Processing command: light on
2025-01-04 16:25:56,350 - INFO - [SERVER] Received packet ID: 1d907a8e-1a3a-41a8-a556-e1102d1136bd
2025-01-04 16:25:56,350 - INFO - Processing command: thermosta get
2025-01-04 16:25:56,350 - ERROR - [ERROR RESPONSE] Unknown device 'thermosta'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2025-01-04 16:25:56,350 - ERROR - [COMMAND ERROR] encrypt_message() missing 1 required positional argument: 'packet_id'
2025-01-04 16:26:03,800 - INFO - [SERVER] Received packet ID: 9f039839-4a09-4d75-924e-ed0da066282a
2025-01-04 16:26:03,800 - INFO - Processing command: thermostat get
2025-01-04 20:22:22,594 - DEBUG - Using proactor: IocpProactor
2025-01-04 20:22:22,596 - INFO - Server is running on 127.0.0.1:12345
2025-01-04 20:22:22,990 - INFO - New connection from ('127.0.0.1', 57691)
2025-01-04 20:22:23,012 - INFO - [INFO] Shared key established with ('127.0.0.1', 57691): 01000000000000000000000000000000
2025-01-04 20:22:59,727 - INFO - [SERVER] Received packet ID for auth: 5df43118-81cd-4b66-a8a1-da1cbfcd8e81
2025-01-04 20:23:08,537 - INFO - [SERVER] Received packet ID: e275bf4a-82fd-4648-b0c5-931645f65c76
2025-01-04 20:23:08,537 - INFO - Processing command: light on
2025-01-04 20:23:12,725 - INFO - [SERVER] Received packet ID: 6042794f-1052-4a6e-a12d-63d75b14b24e
2025-01-04 20:23:12,725 - INFO - Processing command: thermostat get
2025-01-04 20:23:17,652 - INFO - [SERVER] Received packet ID: b342e414-738f-4848-af04-7e31752cd4ea
2025-01-04 20:23:17,652 - INFO - Processing command: thermostat getyy
2025-01-04 20:23:17,652 - ERROR - [ERROR RESPONSE] Invalid action 'getyy' for device 'thermostat'. Valid actions are: get, set.
2025-01-04 20:23:17,652 - ERROR - [COMMAND ERROR] encrypt_message() missing 1 required positional argument: 'packet_id'
2025-01-04 20:23:22,070 - WARNING - [SERVER] Client ('127.0.0.1', 57691) disconnected abruptly.
2025-01-04 20:23:25,379 - INFO - New connection from ('127.0.0.1', 57715)
2025-01-04 20:23:25,396 - INFO - [INFO] Shared key established with ('127.0.0.1', 57715): 04000000000000000000000000000000
2025-01-04 20:23:29,552 - INFO - [SERVER] Received packet ID for auth: bf584645-4e51-49b5-a8b8-3a8358fe090b
2025-01-04 20:28:31,161 - DEBUG - Using proactor: IocpProactor
2025-01-04 20:28:31,163 - INFO - Server is running on 127.0.0.1:12345
2025-01-04 20:28:36,576 - INFO - New connection from ('127.0.0.1', 57921)
2025-01-04 20:28:36,592 - INFO - [INFO] Shared key established with ('127.0.0.1', 57921): 20000000000000000000000000000000
2025-01-04 20:28:50,391 - ERROR - [SERVER ERROR] Unexpected error: cannot access local variable 'username' where it is not associated with a value
2025-01-04 20:28:50,391 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=576 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "c:/Users/enosh/Desktop/Coursework 25'/Network Systems Development/Client-Server network/Server.py", line 319, in handle_client
    if username != HARD_CODED_USERNAME or password != HARD_CODED_PASSWORD:
       ^^^^^^^^
UnboundLocalError: cannot access local variable 'username' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/enosh/Desktop/Coursework 25'/Network Systems Development/Client-Server network/Server.py", line 405, in handle_client
    encrypted_response = encrypt_message(response, shared_key, packet_id)
                                                               ^^^^^^^^^
UnboundLocalError: cannot access local variable 'packet_id' where it is not associated with a value
2025-01-04 20:29:06,456 - INFO - New connection from ('127.0.0.1', 57939)
2025-01-04 20:29:06,473 - INFO - [INFO] Shared key established with ('127.0.0.1', 57939): 02000000000000000000000000000000
2025-01-04 20:29:09,735 - ERROR - [SERVER ERROR] Unexpected error: cannot access local variable 'username' where it is not associated with a value
2025-01-04 20:29:09,735 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=584 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "c:/Users/enosh/Desktop/Coursework 25'/Network Systems Development/Client-Server network/Server.py", line 319, in handle_client
    if username != HARD_CODED_USERNAME or password != HARD_CODED_PASSWORD:
       ^^^^^^^^
UnboundLocalError: cannot access local variable 'username' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/enosh/Desktop/Coursework 25'/Network Systems Development/Client-Server network/Server.py", line 405, in handle_client
    encrypted_response = encrypt_message(response, shared_key, packet_id)
                                                               ^^^^^^^^^
UnboundLocalError: cannot access local variable 'packet_id' where it is not associated with a value
2025-01-04 20:30:02,206 - INFO - New connection from ('127.0.0.1', 57990)
2025-01-04 20:30:02,226 - INFO - [INFO] Shared key established with ('127.0.0.1', 57990): 01000000000000000000000000000000
2025-01-04 20:30:06,603 - ERROR - [SERVER ERROR] Unexpected error: cannot access local variable 'username' where it is not associated with a value
2025-01-04 20:30:06,603 - ERROR - Unhandled exception in client_connected_cb
transport: <_ProactorSocketTransport fd=332 read=<_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>>
Traceback (most recent call last):
  File "c:/Users/enosh/Desktop/Coursework 25'/Network Systems Development/Client-Server network/Server.py", line 319, in handle_client
    if username != HARD_CODED_USERNAME or password != HARD_CODED_PASSWORD:
       ^^^^^^^^
UnboundLocalError: cannot access local variable 'username' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/enosh/Desktop/Coursework 25'/Network Systems Development/Client-Server network/Server.py", line 405, in handle_client
    encrypted_response = encrypt_message(response, shared_key)
                                                               
UnboundLocalError: cannot access local variable 'packet_id' where it is not associated with a value
2025-01-04 20:39:28,662 - DEBUG - Using proactor: IocpProactor
2025-01-04 20:39:28,665 - INFO - Server is running on 127.0.0.1:12345
2025-01-04 20:39:32,454 - INFO - New connection from ('127.0.0.1', 58489)
2025-01-04 20:39:32,472 - INFO - [INFO] Shared key established with ('127.0.0.1', 58489): 10000000000000000000000000000000
2025-01-04 20:39:44,413 - INFO - [SERVER] Received packet ID for auth: 30a63fa4-7566-47db-bafb-f4abaa9e6f08
2025-01-04 20:39:50,097 - INFO - [SERVER] Received packet ID: 47870fb0-0c3a-44e5-ae7d-5f8e64fb403c
2025-01-04 20:39:50,097 - INFO - Processing command: light on
2025-01-04 20:39:58,317 - INFO - [SERVER] Received packet ID: a864f30c-9308-4e50-acee-2566c095677b
2025-01-04 20:39:58,317 - INFO - Processing command: light off
2025-01-04 20:40:02,579 - INFO - [SERVER] Received packet ID: f411a76b-8e7d-4ebe-b316-2b6b1811ed96
2025-01-04 20:40:02,579 - INFO - Processing command: thermostat get
2025-01-04 20:40:14,212 - INFO - [SERVER] Received packet ID: 568f2fe4-96ad-4ba2-82d1-0f1c1cbe6efa
2025-01-04 20:40:14,213 - INFO - Processing command: thermostat set 34
2025-01-04 20:40:18,541 - WARNING - [SERVER] Client ('127.0.0.1', 58489) disconnected abruptly.
2025-01-04 20:40:28,440 - INFO - New connection from ('127.0.0.1', 58563)
2025-01-04 20:40:28,459 - INFO - [INFO] Shared key established with ('127.0.0.1', 58563): 80000000000000000000000000000000
2025-01-04 20:40:32,003 - INFO - [SERVER] Received packet ID for auth: e53f8ce5-8c3b-41f1-89a5-fe2adbb462b0
2025-01-04 20:41:02,138 - DEBUG - Using proactor: IocpProactor
2025-01-04 20:41:02,140 - INFO - Server is running on 127.0.0.1:12345
2025-01-04 20:41:05,695 - INFO - New connection from ('127.0.0.1', 58573)
2025-01-04 20:41:05,711 - INFO - [INFO] Shared key established with ('127.0.0.1', 58573): 40000000000000000000000000000000
2025-01-04 20:41:19,654 - INFO - [SERVER] Received packet ID for auth: 8fc4d841-8feb-45f5-b2cd-eca1db756913
2025-01-04 20:41:24,964 - INFO - [SERVER] Received packet ID: 749e152c-5aaa-4378-90b6-a44b4c50089c
2025-01-04 20:41:24,964 - INFO - Processing command: light on
2025-01-04 20:41:28,830 - INFO - [SERVER] Received packet ID: e08afa73-fe76-46fb-a3bd-679c8959479b
2025-01-04 20:41:28,831 - INFO - Processing command: light off
2025-01-05 16:00:30,606 - DEBUG - Using proactor: IocpProactor
2025-01-05 16:00:30,625 - INFO - Server is running on 127.0.0.1:12345
2025-01-05 16:00:31,634 - INFO - New connection from ('127.0.0.1', 50686)
2025-01-05 16:00:37,892 - INFO - [INFO] Shared key established with ('127.0.0.1', 50686): bfd6190d20da90c71fdca84522ddd0ea
2025-01-05 16:00:52,018 - DEBUG - Using proactor: IocpProactor
2025-01-05 16:00:52,020 - INFO - Server is running on 127.0.0.1:12345
2025-01-05 16:00:57,702 - INFO - New connection from ('127.0.0.1', 50708)
2025-01-05 16:01:06,252 - INFO - [INFO] Shared key established with ('127.0.0.1', 50708): 4cb9a816316ae54a7b5717b9e4ffdb31
2025-01-05 16:01:33,915 - DEBUG - Using proactor: IocpProactor
2025-01-05 16:01:33,919 - INFO - Server is running on 127.0.0.1:12345
2025-01-05 16:01:38,452 - INFO - New connection from ('127.0.0.1', 50720)
2025-01-05 16:01:38,477 - INFO - [INFO] Shared key established with ('127.0.0.1', 50720): 01000000000000000000000000000000
2025-01-05 16:01:43,936 - INFO - [SERVER] Received packet ID for auth: 598a6be4-8900-42a3-9a99-fa438e295c1d
2025-01-05 16:01:51,056 - INFO - New connection from ('127.0.0.1', 50727)
2025-01-05 16:01:51,078 - INFO - [INFO] Shared key established with ('127.0.0.1', 50727): 04000000000000000000000000000000
2025-01-05 16:01:58,994 - INFO - [SERVER] Received packet ID for auth: 63127e66-ac8e-43f4-97ed-810b9f14fb44
2025-01-05 16:02:15,569 - INFO - New connection from ('127.0.0.1', 50743)
2025-01-05 16:02:15,595 - INFO - [INFO] Shared key established with ('127.0.0.1', 50743): 08000000000000000000000000000000
2025-01-05 16:02:23,156 - INFO - [SERVER] Received packet ID for auth: 4ed0729a-5bcd-4087-9c70-788e48b520b0
2025-01-05 16:02:25,989 - INFO - [SERVER] Received packet ID: 8c295d59-68cf-485a-8986-a0eed1737d97
2025-01-05 16:02:25,989 - INFO - Processing command: light on
2025-01-05 16:02:30,556 - INFO - [SERVER] Received packet ID: 31058317-9c65-46be-b8df-bd98792f52a8
2025-01-05 16:02:30,556 - INFO - Processing command: light off
2025-01-05 16:02:34,930 - INFO - [SERVER] Received packet ID: ac6a771e-5e63-44d3-b911-1f2345d21aaf
2025-01-05 16:02:34,931 - INFO - Processing command: ligh off
2025-01-05 16:02:34,931 - ERROR - [ERROR RESPONSE] Unknown device 'ligh'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2025-01-05 16:02:34,931 - ERROR - [COMMAND ERROR] encrypt_message() missing 1 required positional argument: 'packet_id'
2025-01-05 16:02:38,394 - INFO - [SERVER] Received packet ID: c5ed5625-53ac-4ed3-b30c-213b356ad5c9
2025-01-05 16:02:38,395 - INFO - Processing command: light off
2025-01-05 16:02:51,492 - DEBUG - Using proactor: IocpProactor
2025-01-05 16:02:51,496 - INFO - Server is running on 127.0.0.1:12345
2025-01-05 16:02:58,195 - INFO - New connection from ('127.0.0.1', 50752)
2025-01-05 16:02:58,220 - INFO - [INFO] Shared key established with ('127.0.0.1', 50752): 80000000000000000000000000000000
2025-01-05 16:03:06,341 - INFO - [SERVER] Received packet ID for auth: a18349a5-4512-4784-9515-7adeed88ac77
2025-01-05 16:03:08,723 - INFO - [SERVER] Received packet ID: 6f5dc3c4-2327-4781-83eb-c2d7c7c30f0a
2025-01-05 16:03:08,723 - INFO - Processing command: light on
2025-01-05 16:03:29,911 - DEBUG - Using proactor: IocpProactor
2025-01-05 16:03:29,914 - INFO - Server is running on 127.0.0.1:12345
2025-01-05 16:03:33,784 - INFO - New connection from ('127.0.0.1', 50761)
2025-01-05 16:03:33,806 - INFO - [INFO] Shared key established with ('127.0.0.1', 50761): 01000000000000000000000000000000
2025-01-05 16:03:41,961 - INFO - [SERVER] Received packet ID for auth: b6a714db-d19b-4fa4-a73f-9074d7a64716
2025-01-05 16:03:44,600 - INFO - [SERVER] Received packet ID: 4b127e8a-6903-4214-86c2-90a12d77ca23
2025-01-05 16:03:44,601 - INFO - Processing command: light on
2025-01-05 16:03:47,162 - INFO - [SERVER] Received packet ID: 95236104-8ef8-405b-baa5-a3de7eef51c4
2025-01-05 16:03:47,163 - INFO - Processing command: light off
2025-01-05 16:04:15,976 - DEBUG - Using proactor: IocpProactor
2025-01-05 16:04:15,978 - INFO - Server is running on 127.0.0.1:12345
2025-01-05 16:04:25,534 - INFO - New connection from ('127.0.0.1', 50770)
2025-01-05 16:04:25,558 - INFO - [INFO] Shared key established with ('127.0.0.1', 50770): 04000000000000000000000000000000
2025-01-05 16:04:35,454 - INFO - [SERVER] Received packet ID for auth: 30f3924a-b4ad-42cd-b962-7118920c76f5
2025-01-05 16:04:38,769 - INFO - [SERVER] Received packet ID: 7c24cc86-416f-4917-833a-15d897ebf432
2025-01-05 16:04:38,769 - INFO - Processing command: light on
2025-01-05 16:04:42,292 - INFO - [SERVER] Received packet ID: 0634f8d7-7bb3-4e00-b75c-bc82ca9ece1a
2025-01-05 16:04:42,292 - INFO - Processing command: light off
2025-01-05 16:09:49,175 - DEBUG - Using proactor: IocpProactor
2025-01-05 16:09:49,179 - INFO - Server is running on 127.0.0.1:12345
2025-01-05 16:09:54,139 - INFO - New connection from ('127.0.0.1', 50888)
2025-01-05 16:09:54,162 - INFO - [INFO] Shared key established with ('127.0.0.1', 50888): 40000000000000000000000000000000
2025-01-05 16:10:00,693 - INFO - [SERVER] Received packet ID for auth: 139af6ac-7c9e-4717-acfa-e21f886dbbc6
2025-01-05 16:10:03,219 - INFO - [SERVER] Received packet ID: ec784bf4-a170-45e9-8d7d-d79bba89900f
2025-01-05 16:10:03,219 - INFO - Processing command: light on
2025-01-05 16:10:14,232 - INFO - [SERVER] Client ('127.0.0.1', 50888) disconnected.
2025-01-05 16:11:58,818 - DEBUG - Using proactor: IocpProactor
2025-01-05 16:11:58,823 - INFO - Server is running on 127.0.0.1:12345
2025-01-05 16:12:02,497 - INFO - New connection from ('127.0.0.1', 50910)
2025-01-05 16:12:02,523 - INFO - [INFO] Shared key established with ('127.0.0.1', 50910): 40000000000000000000000000000000
2025-01-05 16:12:09,370 - INFO - [SERVER] Received packet ID for auth: 9b99c575-2b2c-4d91-9674-574702f4c7e2
2025-01-05 16:12:11,826 - INFO - [SERVER] Received packet ID: 937b2021-68a4-4888-8036-0c164331a67f
2025-01-05 16:12:11,826 - INFO - Processing command: light on
2025-01-05 16:34:10,271 - DEBUG - Using proactor: IocpProactor
2025-01-05 16:34:10,273 - INFO - Server is running on 127.0.0.1:12345
2025-01-05 16:34:16,579 - DEBUG - Using proactor: IocpProactor
2025-01-05 16:34:16,582 - INFO - Server is running on 127.0.0.1:12345
2025-01-05 16:34:20,795 - INFO - New connection from ('127.0.0.1', 53838)
2025-01-05 16:34:20,821 - INFO - [INFO] Shared key established with ('127.0.0.1', 53838): 01000000000000000000000000000000
2025-01-05 16:34:31,128 - ERROR - [SERVER] Unexpected error: process_command() missing 1 required positional argument: 'packet_id'
2025-01-05 16:44:17,340 - DEBUG - Using proactor: IocpProactor
2025-01-05 16:44:17,343 - INFO - Server is running on 127.0.0.1:12345
2025-01-05 16:44:22,340 - INFO - New connection from ('127.0.0.1', 54013)
2025-01-05 16:44:22,371 - INFO - [INFO] Shared key established with ('127.0.0.1', 54013): 10000000000000000000000000000000
2025-01-05 16:44:33,579 - ERROR - [SERVER] Unexpected error: process_command() missing 1 required positional argument: 'packet_id'
2025-01-05 16:48:36,561 - DEBUG - Using proactor: IocpProactor
2025-01-05 16:48:36,564 - INFO - Server is running on 127.0.0.1:12345
2025-01-05 16:48:41,288 - INFO - New connection from ('127.0.0.1', 54090)
2025-01-05 16:48:41,314 - INFO - [INFO] Shared key established with ('127.0.0.1', 54090): 20000000000000000000000000000000
2025-01-05 16:48:53,154 - ERROR - [SERVER] Unexpected error: process_command() missing 1 required positional argument: 'packet_id'
2025-01-05 16:55:41,606 - DEBUG - Using proactor: IocpProactor
2025-01-05 16:55:41,609 - INFO - Server is running on 127.0.0.1:12345
2025-01-05 16:55:46,012 - INFO - New connection from ('127.0.0.1', 54592)
2025-01-05 16:55:46,037 - INFO - [INFO] Shared key established with ('127.0.0.1', 54592): 04000000000000000000000000000000
2025-01-05 16:56:09,189 - INFO - New connection from ('127.0.0.1', 54659)
2025-01-05 16:56:09,216 - INFO - [INFO] Shared key established with ('127.0.0.1', 54659): 02000000000000000000000000000000
2025-01-05 16:56:19,327 - INFO - [SERVER] Received packet ID: 70817506-0433-48f8-8385-400aff337fd3
2025-01-05 16:56:19,327 - INFO - [SERVER] Processing command: light on
2025-01-05 16:56:19,327 - INFO - Processing command: light on
2025-01-05 16:56:21,999 - INFO - [SERVER] Received packet ID: fc0c3c11-75d5-413a-a0bc-f539259edbf7
2025-01-05 16:56:22,000 - INFO - [SERVER] Processing command: ligt off
2025-01-05 16:56:22,000 - INFO - Processing command: ligt off
2025-01-05 16:56:22,000 - ERROR - [ERROR RESPONSE] Unknown device 'ligt'. Valid devices are: light, fan, thermostat, smart lock, camera, speaker.
2025-01-05 16:56:22,000 - ERROR - [COMMAND ERROR] encrypt_message() missing 1 required positional argument: 'packet_id'
2025-01-05 16:56:27,331 - INFO - [SERVER] Received packet ID: 1ea136d8-6056-44df-8a71-87cbe3510dd1
2025-01-05 16:56:27,331 - INFO - [SERVER] Processing command: thermostat get
2025-01-05 16:56:27,331 - INFO - Processing command: thermostat get
2025-01-05 16:56:32,500 - INFO - [SERVER] Received packet ID: 3c4bc5c5-433b-415b-837c-2a65d53d5e5e
2025-01-05 16:56:32,500 - INFO - [SERVER] Processing command: thermostat set 23
2025-01-05 16:56:32,500 - INFO - Processing command: thermostat set 23
2025-01-06 11:36:46,979 - DEBUG - Using proactor: IocpProactor
2025-01-06 11:36:46,983 - INFO - Server is running on 127.0.0.1:12345
2025-01-06 11:36:47,219 - INFO - New connection from ('127.0.0.1', 61339)
2025-01-06 11:36:47,249 - INFO - [INFO] Shared key established with ('127.0.0.1', 61339): 01000000000000000000000000000000
2025-01-06 11:36:57,751 - INFO - [SERVER] Received packet ID: ee197ec6-8b49-4f9e-b578-d81c9545e5c1
2025-01-06 11:36:57,752 - INFO - [SERVER] Processing command: light on
2025-01-06 11:36:57,752 - INFO - Processing command: light on
2025-01-06 11:36:59,974 - INFO - [SERVER] Received packet ID: 04c81ede-4ffd-431e-b27d-840ded0c9ff5
2025-01-06 11:36:59,975 - INFO - [SERVER] Processing command: light off
2025-01-06 11:36:59,975 - INFO - Processing command: light off
2025-01-06 11:37:04,462 - INFO - [SERVER] Received packet ID: 57fb2c30-1671-488e-8ac3-cd38f56b29e0
2025-01-06 11:37:04,462 - INFO - [SERVER] Processing command: thermostat get
2025-01-06 11:37:04,462 - INFO - Processing command: thermostat get
2025-01-06 11:37:19,888 - INFO - [SERVER] Received packet ID: 2a4a43fb-bd5c-47a3-b4e1-5e5ab0b8fbf6
2025-01-06 11:37:19,888 - INFO - [SERVER] Processing command: thermostat set 24
2025-01-06 11:37:19,888 - INFO - Processing command: thermostat set 24
2025-01-06 11:37:27,932 - INFO - [SERVER] Received packet ID: e6b59232-c062-4548-ba94-e118bd869f59
2025-01-06 11:37:27,934 - INFO - [SERVER] Processing command: fan on
2025-01-06 11:37:27,934 - INFO - Processing command: fan on
2025-01-06 11:37:38,559 - INFO - [SERVER] Received packet ID: d24bbdc8-56a4-4f05-8742-87b979f5bc01
2025-01-06 11:37:38,560 - INFO - [SERVER] Processing command: fan high
2025-01-06 11:37:38,560 - INFO - Processing command: fan high
2025-01-06 11:37:49,738 - INFO - [SERVER] Received packet ID: a688e9a3-f813-49ba-a85e-85eebdae54b1
2025-01-06 11:37:49,738 - INFO - [SERVER] Processing command: smart lock locked
2025-01-06 11:37:49,738 - INFO - Processing command: smart lock locked
2025-01-06 11:37:53,384 - INFO - [SERVER] Received packet ID: 99b45727-f50c-43d6-97cb-52839bb486cf
2025-01-06 11:37:53,384 - INFO - [SERVER] Processing command: speaker on
2025-01-06 11:37:53,384 - INFO - Processing command: speaker on
2025-01-06 11:37:56,522 - INFO - [SERVER] Received packet ID: a4f20c18-00dd-44e6-b7b7-22fbe259360d
2025-01-06 11:37:56,522 - INFO - [SERVER] Processing command: camera on
2025-01-06 11:37:56,523 - INFO - Processing command: camera on
2025-01-06 11:38:06,945 - INFO - [SERVER] Received packet ID: 05a34f7f-71b8-47c4-b034-089bafde5f1f
2025-01-06 11:38:06,945 - INFO - [SERVER] Processing command: smart lock lock 4:45pm
2025-01-06 11:38:06,945 - INFO - Processing command: smart lock lock 4:45pm
2025-01-06 11:38:12,901 - INFO - [SERVER] Received packet ID: ae04adec-b05c-47f8-bd01-b510cc5b9b35
2025-01-06 11:38:12,901 - INFO - [SERVER] Processing command: light of
2025-01-06 11:38:12,901 - INFO - Processing command: light of
2025-01-06 11:38:12,901 - ERROR - [ERROR RESPONSE] Invalid action 'of' for device 'light'. Valid actions are: on, off.
2025-01-06 11:38:12,903 - ERROR - [COMMAND ERROR] encrypt_message() missing 1 required positional argument: 'packet_id'
